### PR TITLE
:hammer: Automatically generate resources files with cmake

### LINKED ISSUE #3949: Our resource system is confusing
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

Our tooling does not indicate that generate_resources.py should be executed. We should have a script that checks if `resources/` was modified and lints/blocks the PR from being accidentally merged.

[20:30:39.071] Mm2PL: actually we have a clang-tidy ci thingy, i could just massage it to check for resources changes Hmmm 
[20:30:50.430] Mm2PL: we could just have it suggest new changes to autogen files 
[20:31:05.511] Mm2PL: no need to have people run the stupid script and complain how stupid it is
[20:31:07.476] Mm2PL: KKoooona
[20:31:23.516] pajlada: KKoooona 

### Screenshots

n/a

### OS and Chatterino Version

n/a - development tooling issue

### PR DESCRIPTION
**Pull request by AnotherFoxGuy**
This PR replaces `resources/generate_resources.py` with a cmake script that will automatically generate the required resource files

Todo:
- [x] Test on Windows with QtCreator
- [x] Test on Windows with proper building
- [x] Test on Linux
- [x] Test on Mac
- [x] Maybe move the generated files to the build folder? (Needs to be discussed)
- [x] Update  `CHANGELOG.md` 

Fixes #3949

### CODE REVIEW

**Comment by pajlada** [comment]
Looks great, this approach looks good to me. Thank you for taking the effort and looking into this!

Poke me whenever you feel this is ready for a proper review or if you need a Linux tester.

**Comment by dnsge** [comment]
Works on macOS 👍 

My editor also finds the `ResourcesAutogen.hpp` header file with no problem, so no broken autocomplete which is great.

**Comment by Felanbird** [comment]
image
conan fail is unrelated to this PR, I've just been ignoring it

**Comment by Felanbird** [comment]
QtCreator on windows is 🆗 now

**Comment by kornes** [comment]
tested 6497570d0f81d4c59e64759608835a12aed10806 with vcpkg on windows and works fine
great change 👍

**Comment by AnotherFoxGuy** [comment]
@pajlada This PR should be ready for a review now

**Comment by pajlada** [comment]
Code looks good, testing Linux vim experience now

**Review by pajlada — APPROVED** [review]
Linux vim experience works great :+1:

**Comment by pajlada** [comment]
Is there any further testing you would want before haaving this merged in @AnotherFoxGuy ?

**Comment by AnotherFoxGuy** [comment]
> Is there any further testing you would want before having this merged?

I think that it has been tested on all platforms now, so I think it is ready to merge

**Pull request merged**
