### PR TITLE
Fix the reconnection backoff accidentally resetting when thrown out of certain IRC servers

### LINKED ISSUE #3313: [IRC] Chatterino keeps trying to reconnect every 1 second
**Describe your issue**
Chatterino keeps reconnecting to IRC servers every one second in case of failure (?). This is problematic because it triggers rate limiting on remote servers. It should reconnect slower or with a exponential backoff

**OS and Chatterino Version**
Windows 10; 2.3.4

### PR DESCRIPTION
**Pull request by pajlada**
- Only reset reconnect backoff when we can confirm a successful connection was made
- Add changelog entry

Pull request checklist:

- [x] `CHANGELOG.md` was updated, if applicable

# Description

Fixes #3313

### CODE REVIEW

**Review by Felanbird — COMMENTED** [review]
As a note, this caps out at 8 second [1->2->4->8] reconnect time. We discussed 16 seconds on stream but I'm unsure where the limitation is set.

**Comment by Mm2PL** [comment]
@Felanbird it's set right here :) https://github.com/Chatterino/chatterino2/blob/fix/dont-reset-reconnection-backoff/src/providers/irc/IrcConnection2.hpp#L34

**Comment by Felanbird** [comment]
> 
> 
> @Felanbird it's set right here :) https://github.com/Chatterino/chatterino2/blob/fix/dont-reset-reconnection-backoff/src/providers/irc/IrcConnection2.hpp#L34

👍 - I misunderstood the purpose of the `<4>` when playing with it myself

**Comment by pajlada** [comment]
Looks good to me
image

**Pull request merged**
