### PR TITLE
Fix missing parent of tooltips for Wayland

### PR DESCRIPTION
**Pull request by crazysmc**
In response to issue #3501

Each widget that uses TooltipWidget gets its own instance of it with itself as a parent set.

That fixes the issue for me on Wayland. Although I'm not using a tiling WM, the parent-less tooltips appeared in the wrong place before.

### CODE REVIEW

**Comment by ilya-zlobintsev** [comment]
This seems to solve the issue for me on Arch Linux using KDE 5.27. Tested on both QT5 and QT6.

**Comment by ilya-zlobintsev** [comment]
I've also tested sway - the behaviour is slightly different, the previews don't show up at all when hovering over something when the window is unfocused, but IMO that is fine as well

**Comment by Nerixyz** [comment]
Seems to work on Windows 10 with Qt 6. Works when the window is unfocused. Only thing I noticed is that tooltips will stay when the window is resized, but shouldn't be an issue.

**Review by pajlada — APPROVED** [review]
Thank you! Works as expected on Arch Linux w/ i3

As a first-time contributor, you can now add yourself to the contributors list that's shown inside the About page in Chatterino.

If you want this, you can open a new PR where you modify the `resources/contributors.txt` file and add yourself to the list. Make sure to read the comments at the top for instructions.

**Pull request merged**
