### PR TITLE
Use an archive link for OpenSSL 1.1.1s in BUILDING_ON_WINDOWS.md

### PR DESCRIPTION
**Pull request by Sheepposu**
Pull request checklist:

- [x] `CHANGELOG.md` was updated, if applicable

# Description
The current link (https://slproweb.com/download/Win64OpenSSL-1_1_1s.exe) is dead and replacing it with (https://web.archive.org/web/20221101204129/https://slproweb.com/download/Win64OpenSSL-1_1_1s.exe) fixes this.

### CODE REVIEW

**Comment by Felanbird** [comment]
It's dead because slproweb only offers the currently stable version of OpenSSL, if you'd like to update it, change it to `t`

**Comment by Sheepposu** [comment]
Ah I see. Would using version t instead of s affect anything though?

**Comment by Felanbird** [comment]
> Ah I see. Would using version t instead of s affect anything though?

🤷, won't know until we try

**Review by Felanbird — APPROVED** [review]

**Comment by Felanbird** [comment]
I'll merge this since #4413 removed the section stating what to do if there the link is broken

Thanks 👍

**Pull request merged**
