### PR TITLE
Load 100 blocked users instead of default 20

### PR DESCRIPTION
**Pull request by iProdigy**
Pull request checklist:

- [x] `CHANGELOG.md` was updated, if applicable

# Description

Work towards #2767 so that at least up to 100 blocked users are returned rather than the default 20

### CODE REVIEW

**Comment by fourtf** [comment]
For some wild reason the "count" is actually called "first". Haven't tested but should work.

https://dev.twitch.tv/docs/api/reference#get-user-block-list

**Comment by zneix** [comment]
I think that following pagination to load all the blocks is a better solution, however this is better than nothing.

**Comment by jammehcow** [comment]
Might be nicer to paginate the blocked users page so that we can return a decent chunk. Might be too bloated for current settings layout though

**Comment by pajlada** [comment]
> I think that following pagination to load all the blocks is a better solution, however this is better than nothing.

Pagination would definitely be what we want to do, but even with a pagination PR we'd want to increase the limit to 100 so this is a good first step

**Review by pajlada — APPROVED** [review]

**Review by zneix — APPROVED** [review]
Fair point, I agree with paj.

**Pull request merged**
