### PR TITLE
fix: parenting logic, fixing some windows & tooltips misbehaving

### LINKED ISSUE #5432: [Wayland] Drag and Drop breaks tooltips
### Checklist

- [ ] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Hyprland (broken)

```shell
$ hyprctl version
Hyprland, built from branch  at commit cba1ade848feac44b2eda677503900639581c3f4  (props: bump version to 0.40.0).
```

https://github.com/Chatterino/chatterino2/assets/40008647/a03a3f63-7283-4372-8774-99fb91a3b6a5

### Sway (works)

```shell
$ sway --version
sway version 1.9
```

https://github.com/Chatterino/chatterino2/assets/40008647/141e25d7-e483-44b9-b522-3c626932ff05

### Screenshots

_No response_

### OS and Chatterino Version

Chatterino 2.5.1 (commit 9ec102240) built with Qt 6.7.1 Running on Arch Linux, kernel: 6.9.2-arch1-1

### LINKED ISSUE #5521: Drag and Drop Causing Child Windows to Disappear
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

Opening a search window or pinning open a usercard on a chat behaves as normal until the parent chat is directly moved using the drag and drop system.  After which any and all such windows belonging to that chat will disappear but still exist.  Even if the chat is returned to it's starting position. These windows are all completely inaccessible and will only appear again when trying to move the same chat again, disappearing once dropped into place.

Moving other chats via the drag/drop system does not affect the child windows of other chats.

### Screenshots

https://github.com/user-attachments/assets/0307e3ec-308f-4740-ad4a-72b8a8ffc40a

### OS and Chatterino Version

commit 44abb190 from 2024-07-20 running on Windows 10 version 22H2

### PR DESCRIPTION
**Pull request by pajlada**
This needs testing on all platforms

Fixes #5432
Fixes #5521

### CODE REVIEW

**Comment by pajlada** [comment]
What I need tested:
1) Do tooltips work (not the bounds checking) before & after moving a split?
2) Does the Input Completion Popup work (not the bounds checking) before & after moving a split?
3) Does the Search popup work (i.e. not closing or being moved into the split somehow) before & after moving a split?

**Comment by Nerixyz** [comment]
https://github.com/user-attachments/assets/16aa4154-80aa-40e0-9655-df68f588daab

Works on Windows.

**Comment by pajlada** [comment]
Works as expected on my mac mini (except the search popup X button randomly closed the entire app without it being a crash - it happened 3 times then never again. I think there's a fairy somewhere in my macmini that caused it to do that to make me go insane)

Works as expected on X11 with i3. The only weird thing is that when I move the split, it moves up & to the left by ~1 pixel.

**Comment by pajlada** [comment]
image

**Pull request merged**
