### PR TITLE
Allow customization of Twitch chat server parameters through ENV variables

### PR DESCRIPTION
**Pull request by pajlada**
This would leave an option for https://github.com/Chatterino/chatterino2/issues/1296 if compiling their own version isn't viable

### CODE REVIEW

**Comment by fourtf** [comment]
We could also add a setting for choosing ws+tsl/tsl/raw irc.

**Comment by pajlada** [comment]
Yup, could also do that. Is there a point in defaulting to 443? It looks like the most compatible one, but I don't know if there are any downsides to using it.

**Comment by fourtf** [comment]
@pajlada that's actually 5Head since it will get around proxies

**Comment by pajlada** [comment]
I am closing the PR and moving default port to 443 instead of 6697

**Pull request closed without merging**
