### PR TITLE
Added system message on new date

### LINKED ISSUE #1016: Add a message separating days after 12 am
Some messages may have been sent weeks or days apart.
When loading chat history and encountering such, i suggest to add a date label split.

<details>
  <summary>Currently at Ch2 (screenshot)</summary>
  

</details>

<details>
  <summary>Desirable behaviour (screenshot of example in another app)</summary>
  

(it is Telegram Desktop)
</details>

### PR DESCRIPTION
**Pull request by apa420**
Pull request checklist:

- [x] `CHANGELOG.md` was updated, if applicable

# Description
Closes #1016

Displays the date in local format.
(Old pr #2021)

### CODE REVIEW

**Comment by apa420** [comment]
Should there be a white line like in the previous pr, then I'd need to add another system message flag thing for it.

**Review by pajlada — CHANGES_REQUESTED** [review]
Instead of relying on a signal, we're most likely best off comparing the date when a new message is added to a Channel to the date of the last added message, and if those dates differ, add a new system message before the incoming message stating the date change.

See `Channel::addMessage` in `src/common/Channel.cpp`
See https://doc.qt.io/qt-5/qdate.html#operator-not-eq

**Comment by apa420** [comment]
It works!
Thanks zneix for helping me test!

**Comment by apa420** [comment]
Now also implemented support for history messages.
It will start the chat with the date the message was sent on if and only if the date isn't the current one.
I could change this to make it ALWAYS show the date at the top.
Which honestly would make more sense imo.

**Review by zneix — APPROVED** [review]

**Review by pajlada — APPROVED** [review]
LGTM :+1:

**Pull request merged**
