### PR TITLE
Fix quotation and handling of additional streamlink options

### LINKED ISSUE #2458: ([Errno 2] No such file or directory: 'mpv --no-cache')
I use streamlink with a custom path and multiple additional options, one of them is **-p "mpv --no-cache"** . I updated today to r3034.7d9f4c2b-1 from r2997.a6e23e24-1 and now when i try to open the command through chatterino i get the title error. If i paste the command on my shell there is no error and the stream starts.

Right now i downgraded to r2997 which works correctly. Thanks a lot!

chatterino output:
[cli][info] Found matching plugin twitch for URL twitch.tv/nymn
[cli][info] Available streams: audio_only, 160p (worst), 360p, 480p, 720p, 720p60, 1080p60 (best)
[cli][info] Opening stream: 720p60 (hls)
[cli][info] Starting player:  "mpv --no-cache"
error: Failed to start player:  "mpv --no-cache" ([Errno 2] No such file or directory: 'mpv --no-cache': 'mpv --no-cache')
[cli][info] Closing currently open stream...

shell output (bash/fish on Manjaro/Debian):
[cli][info] Available streams: audio_only, 160p (worst), 360p, 480p, 720p, 720p60, 1080p60 (best)
[cli][info] Opening stream: 720p60 (hls)
[plugins.twitch][info] Will skip ad segments
[plugins.twitch][info] Low latency streaming (HLS live edge: 1)
[plugins.twitch][info] Waiting for pre-roll ads to finish, be patient
[stream.hls][info] Filtering out segments and pausing stream output
[cli][info] Starting player: mpv --no-cache
[stream.hls][info] Resuming stream output

It seems chatterino now is not able to pass the quotes argument correctly.

### PR DESCRIPTION
**Pull request by EmilGedda**
Pull request checklist:

- [x] `CHANGELOG.md` was updated, if applicable

# Description
[This change](https://github.com/Chatterino/chatterino2/commit/185980f8a2d94b61265e84362f1d76bfe2abab7c#diff-ec7a528a6fc8ad2fa5641c962e9c22c6514ae44dc55debd3e66f1c765d757495R190) broke streamlink additional options with arguments (such as `--hls-live-edge 1`) and also quoted arguments (such as `-p "mpv --no-cache"`), as all specified additional arguments were passed as one instead of multiple.

This change fixes quotation and properly splits the additional arguments.
Closes #2458

### CODE REVIEW

**Review by leon-richardt — CHANGES_REQUESTED** [review]
Ubuntu builds on Qt 5.12.10 fail because [`QProcess::splitCommand` only exists since Qt 5.15](https://doc.qt.io/qt-5/qprocess.html#splitCommand). The [Windows build also fails](https://github.com/Chatterino/chatterino2/pull/2495/checks?check_run_id=2033131292#step:10:384), although GitHub Actions reports it as successful.

Currently, we require Qt 5.12 as minimum version so we would need to roll our own solution for the time being.

**Edit:** As a mirror, I have created a G[ist with the source code for `QProcess::splitCommand`](https://gist.github.com/leon-richardt/43fac15da368c4cadb00adf9a8dd30d2) as implemented in Qt 5.15. We could "backport" that implementation until we raise the minimum version.

**Comment by EmilGedda** [comment]
Thanks for spotting that.
I decided to backport `splitCommand` from the gist of yours, cheers for that. 
It's in its own file and should be very pain free to remove next version bump of QT.

**Comment by EmilGedda** [comment]
CI seems to fail with something unrelated at the moment and probably needs to be rerun.

**Comment by zneix** [comment]
Hey, sorry for introducing this issue - I use streamlinkrc for streamlink config so I had no idea my change would break arguments passed via the setting.
Although, I think the changelog entry is rather unnecessary since the bug was introduced after latest stable and beta releases; maybe you can append the number of this pull request to the changelog entry with addition of `/streamlink` command (line 57 atm).

**Comment by pajlada** [comment]
The change @zneix mentioned seems good to me - we will need to wait with merging this in until I've fixed the macOS CI stuff (being done in #2500 atm)

**Comment by EmilGedda** [comment]
> Although, I think the changelog entry is rather unnecessary since the bug was introduced after latest stable and beta releases; maybe you can append the number of this pull request to the changelog entry with addition of `/streamlink` command (line 57 atm).

Fixed

**Review by pajlada — APPROVED** [review]
Looks good to me! Thank you for your contribution! :+1: 

If you would like to be added to the contributors list in the About page of the application, please follow the instructions at the top of the https://raw.githubusercontent.com/Chatterino/chatterino2/master/resources/contributors.txt file and create a new PR

**Pull request merged**
