### PR TITLE
Add mod button-like placeholders in right click commands

### PR DESCRIPTION
**Pull request by Mm2PL**
Pull request checklist:

- [x] `CHANGELOG.md` was updated, if applicable
- [x] swap context lookup order

# Description

This also adds new placeholder `input.text` which returns the text the user has in their SplitInput. I've also changed behavior of CommandController to use variables given to it first then try to use global ones.

Some things I came up with:

<table>
<tr>
	<td><code class=notranslate>/reply
	<td><code class=notranslate>/raw @reply-parent-msg-id={msg.id} PRIVMSG #{channel.name} :{input.text}
	<td> Sends a Twitch reply with the given text
<tr>
	<td><code class=notranslate>/quote_reply
	<td><code class=notranslate>/raw @reply-parent-msg-id={msg.id} PRIVMSG #{channel.name} :{input.text} > {1+}
	<td> Sends a Twitch reply with the selected text/whole message
<tr>
	<td> <code class=notranslate>/translate
	<td> <code class=notranslate>/openurl https://translate.google.com/?sl=auto&tl=en&text={1+}&op=translate
	<td> Opens Google Translate with the given message/selection
</table>

You can somewhat use right-click commands like normal ones even with custom placeholders:
<table>
<tr>
	<td><code class=notranslate>/testing
	<td><code class=notranslate>/testing {input.text;NaM}
	<td> Will send <code class=notranslate>testing {text in split input}</code> if used from right-click command or <code class=notranslate>NaM</code> if not
</table>

### CODE REVIEW

**Comment by xel86** [comment]
Tested and works great! Thanks mm2pl

**Comment by zneix** [comment]
After a brief look code looks good, I'll test these changes later on 👌

**Review by xHeaveny — COMMENTED** [review]
yea it works good

**Review by pajlada — APPROVED** [review]
Works as expected! Merge this it when you're happy with it @zneix

**Review by zneix — APPROVED** [review]

**Pull request merged**
