### PR TITLE
Better support for compiling with system libraries

### PR DESCRIPTION
**Pull request by pajlada**
#1444

### CODE REVIEW

**Comment by pajlada** [comment]
@tim77 
I have added build options for:
```
fmt
rapidjson
websocketpp
```

however, for `libcommuni` we use our own fork for some important irc-related fixes.
On my machine, I was only able to use the rapidjson system library, both fmt and websocketpp had issuues with their system variant.
For fmt, it's just a matter of the version being wrong.
For websocketpp, the version was correct but there had been a patch applied by the arch linux maintainer which made it not work for us.

Please let me know if this fixes your issue, and if not, what I can do to fix it.

**Comment by tim77** [comment]
Good news: chatterino2 packaged for official Fedora repos and now [on QA](https://bodhi.fedoraproject.org/updates/FEDORA-2019-8139b22c6b), but many maintainers still insist that we should use system libs and asking why not push to upstream this patches?

I'll try to build with system `rapidjson` now... At least this something. Thank you.

**Comment by tim77** [comment]
> For fmt, it's just a matter of the version being wrong.

Would it possible to port on actual version 6?

**Comment by xvitaly** [comment]
Hardocoding of paths is not good.

You should use pkg-config. qmake has its support. Just use something like this:

```
CONFIG += link_pkgconfig
PKGCONFIG += fmt
```

**Comment by xvitaly** [comment]
`CONFIG += link_pkgconfig` should be added to main config and `PKGCONFIG += fmt` - to `fmt.pri`.

Pkg-config will automatically find library, its headers and specify correct compiler/linker options.

**Comment by pajlada** [comment]
> > For fmt, it's just a matter of the version being wrong.
> 
> Would it possible to port on actual version 6?

Definitely possible yeah



> `CONFIG += link_pkgconfig` should be added to main config and `PKGCONFIG += fmt` - to `fmt.pri`.
> 
> Pkg-config will automatically find library, its headers and specify correct compiler/linker options.

Thanks! looking into this

**Pull request merged**
