### PR TITLE
Handle non-versioned annotated tags gracefully when building a Ubuntu .deb package

### PR DESCRIPTION
**Pull request by Wissididom**
Pull request checklist:

- [x] `CHANGELOG.md` was updated, if applicable

# Description

pajlada: "If you want to improve this, I'd rather it be done in a separate PR so we can nitpick over it without blocking the main purpose of the PR" from https://github.com/Chatterino/chatterino2/pull/4374

### CODE REVIEW

**Comment by Felanbird** [comment]
I mean there's no world where we are doing this and calling it `ightly-build` right? 
If we are going to make this change we have to refactor this area to strip where we need it and not strip where we don't.

**Comment by pajlada** [comment]
I think a better approach is to see if the tag we found starts with v, and if it does, cut the first character and use that as the version. if the tag we found does not start with v, just use `0.0.0-dev`

**Comment by Wissididom** [comment]
The initial thought why I implemented it was that nightly-build became the latest release after force pushing so 2.4.0 wasn't the latest tag anymore

**Comment by Wissididom** [comment]
Tested latest commit with
```
chatterino_version="v2.4.0"
#chatterino_version="nightly-build"
#chatterino_version=""
if [[ ${chatterino_version:0:1} == 'v' ]]; then
    chatterino_version=${chatterino_version:1}
else
    chatterino_version="0.0.0-dev"
fi
echo $chatterino_version
```
on my local machine while changing the first three line each try

**Review by pajlada — APPROVED** [review]

**Pull request merged**
