### PR TITLE
fix error on remove items in settings due to signal vector model

### PR DESCRIPTION
**Pull request by hemirt**
fixes an access violation (null) when removing items in settings menu

### CODE REVIEW

**Comment by pajlada** [comment]
What are some things that crashed before but does not crash now?

**Comment by hemirt** [comment]
@pajlada removing a highlight phrase

**Comment by pajlada** [comment]
> @pajlada removing a highlight phrase

I'm unable to reproduce the issue on Windows and Linux, is there anything more specific you need to do to experience the crash?

**Comment by hemirt** [comment]
i just got nightly, used the debug build and got the crashes on removing it, its probably something about having a different kind of settings json file or inconsistency in it, anyways this check is always correct against crashes (read out of bounds) and its only on the delete functions, so it shouldnt even be a bottleneck at all, it could fix some crashes for some, and do nothing detrimental anyways, ergo i believe it should be put in anyways

**Comment by apa420** [comment]
would be nice to see what could cause it, do you mind posting your config - personal stuff?

**Comment by hemirt** [comment]
@apa420 tried removing everything in %appdata% folder and then the steps, still crashed, guess it wasnt in the files (since they got auto regernerated)

**Comment by hemirt** [comment]
maybe it depends on qt version, mine is 5.11.0 atm

(5.12.3 didnt like the custom title bar 
image
and added the windows on top of it )

**Comment by apa420** [comment]
So does the nightly crash?
Or only the version you built yourself?

**Comment by hemirt** [comment]
nightly downloaded from releases with everything in %appdata%/chatterino2 deleted, crashes @apa420

**Comment by hemirt** [comment]
What even is the purpose of that assert? Shouldnt it just be an if and return NoItemFlags instead?

**Comment by hemirt** [comment]
Shouldnt it just use https://doc.qt.io/qt-5/qmodelindex.html#isValid

**Pull request closed without merging**
