### PR TITLE
fix: re-add missing Twitch emote reload message

### LINKED ISSUE #3644: Reloading subscriber emotes no longer shows system message
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

In #3135 a system message was added to tell the user Twitch emotes were loaded. This no longer happens as of df70ca59e3ad48f47579329689dfdaa2c2659833 - most likely due to an accidental deletion. 

### Screenshots

image

### OS and Chatterino Version

Chatterino 2.3.5-beta1 (commit 28fa6b8f5)

### PR DESCRIPTION
**Pull request by jammehcow**
Pull request checklist:

- [ ] `CHANGELOG.md` was updated, if applicable

# Description

This PR aims to fix #3644 by re-adding the system message.

image

### CODE REVIEW

**Comment by jammehcow** [comment]
No changelog needed, fixes a "regression".

**Review by Felanbird — APPROVED** [review]
literally looks like the original PR so 👍

**Review by Felanbird — CHANGES_REQUESTED** [review]
I'm taking back my approval
image

**Comment by jammehcow** [comment]
> I'm taking back my approval

Good catch. I assume the IVR request is executing multiple times - will look at that later today.

**Comment by jammehcow** [comment]
Fixed in [1562d80](https://github.com/Chatterino/chatterino2/pull/3645/commits/1562d80db66fc15fee2f64d927779a8fc0285e42)

**Review by Felanbird — APPROVED** [review]
it fixed

**Review by pajlada — APPROVED** [review]

**Pull request merged**
