### PR TITLE
Don't grab the keyboard in channel picker dialog

### LINKED ISSUE #2835: "Add split" dialog can't be moved with WM hotkeys
**Describe your issue**
When attempting to move the "new split" dialog using WM keybinds (e.g. super + right_arrow) the super key is ignored. This causes the arrow keys (if used for window movement) to act as if they weren't in a key combination. The window also does not move.

The only way I've managed to get around this is to Super + Tab (my bind for switching to recent workspace) which has to be done twice in order for it to register. Seems like the super key is somehow being captured?

**Screenshots**
Example behaviour when moving with Super + {left,right} in bspwm:
https://user-images.githubusercontent.com/4962764/120067828-c4f4af80-c0d1-11eb-838f-6388336a58c9.mp4

**OS and Chatterino Version**
Arch Linux, linux-zen 5.12.7
bspwm + sxhkd, picom
Chatterino 2.3.2 (commit 3fddafb)

### PR DESCRIPTION
**Pull request by Mm2PL**
Pull request checklist:

- [x] `CHANGELOG.md` was updated, if applicable

# Description

## WIP

Fixes #2835

### CODE REVIEW

**Comment by Mm2PL** [comment]
Needs testing to see if i didn't break anything on Windows and MacOS. It works as I'd expect it to on Arch Linux btw.

**Review by Felanbird — APPROVED** [review]
Functionality works the same on windows, arrow keys & `tab` both allow for scrolling through the options as expected, as well as when using the native "move" function on windows `alt+spacebar`, the functionality works the same as before (since there's no super button I had to figure out some equiv to test).

**Comment by Felanbird** [comment]
Minor note: I noticed both pre and post fix, numpad arrow keys are unable to scroll past Live (bottom) and Channel (top) respectively the way normal arrow-up and arrow-down can [looping around the custom channel picker dialog], but that's unrelated to this issue.

**Comment by Felanbird** [comment]
@LosFarmosCTL I require one macOS review please :)

**Comment by LosFarmosCTL** [comment]
> @LosFarmosCTL I require one macOS review please :)

I’m with my parents this weekend, I can test it as soon as I am back home again sometime this evening.

**Comment by Felanbird** [comment]
> I’m with my parents this weekend, I can test it as soon as I am back home again sometime this evening.

no worries he's playing WoW anyway.

**Review by pajlada — APPROVED** [review]

**Comment by pajlada** [comment]
Happy to merge in once you've given it a little try macos-expert LosFarmosCTL :heart:

**Comment by LosFarmosCTL** [comment]
Changes work as expected under macOS, I am now able to move the window using my WM (yabai) and the keybindings still work just like before, seems good to me.

**Review by LosFarmosCTL — APPROVED** [review]

**Pull request merged**
