### PR TITLE
added /requests command

### PR DESCRIPTION
**Pull request by badoge**
Pull request checklist:

- [x] `CHANGELOG.md` was updated, if applicable

# Description

Opens the current channel's reward queue, can also take an input to open some other channel's queue.

### CODE REVIEW

**Review by zneix — CHANGES_REQUESTED** [review]
I'm sorry but I'm going to deny this one. With `/openurl` and the extended placeholders that were added in #3155 you can create many creative commands like this one on your own, e.g.:
c2 commands 101

I just don't want extra code for something that doesn't need it at all.

**Comment by zneix** [comment]
On the other note, perhaps a little section with "examples" of how command placeholders can be used might be a cool addition - this PR alone being created in the first place shows that it is not as commonly known that these super useful placeholders exist. Just to show users that they can have something without much effort and show them how to do that.

**Comment by badoge** [comment]
I added it because it's a command in webchat https://help.twitch.tv/s/article/chat-commands?language=en_US#AllMods

i thought chatterino was meant to match as many default twitch commands as possible FeelsDankMan

**Comment by zneix** [comment]
> I added it because it's a command in webchat [help.twitch.tv/s/article/chat-commands?language=en_US#AllMods](https://help.twitch.tv/s/article/chat-commands?language=en_US#AllMods)

Oh, this is a completely different reasoning then. I had 0 Clue that such command exists in webchat. If it does then sure, we can add this. (Although it doesn't show up in `.help`'s output at all, weird.

**Comment by Mm2PL** [comment]
17 maj 2022 11:41:16 Kasia ***@***.***>:

> I had 0 Clue that such command exists in webchat.
I'm 99% sure it's a new command. I also thought this was a new custom thing.

**Review by Mm2PL — DISMISSED** [review]
Change the brackets. Might be good to add this into the commands list on the wiki: https://github.com/Chatterino/wiki/blob/master/docs/Commands.md

**Comment by Felanbird** [comment]
> Change the brackets. Might be good to add this into the commands list on the wiki: [https://github.com/Chatterino/wiki/blob/master/docs/Commands.md](https://github.com/Chatterino/wiki/blob/master/docs/Commands.md?rgh-link-date=2022-05-17T11%3A04%3A58Z)

I was thinking of this, but since it's a webchat command I didn't mention it, since we mainly went with commands that have some sort of separate functionality for that wiki page.

**Review by pajlada — APPROVED** [review]

**Review by zneix — APPROVED** [review]

**Pull request merged**
