### PR TITLE
Fix link parsing in IRC

### LINKED ISSUE #1380: Links are not clickable in IRC channels
**Describe the bug**
Links appear as regular text, non-clickable

**To Reproduce**
Post a link, try to click, nothing.

**Expected behavior**
Post a link, try to click, a web page opens in your favorite web browser.

**Chatterino version**
Chatterino Nightly 2.1.5 (commit d200f12f4, 27.09.2019) (randers minimod fork)

### LINKED ISSUE #1865: [IRC] Text with linebreaks has spaces when copied
**Describe the bug**
If you post text that is so long that it wraps to next line, copypaste of that text will contain a space at the place it broke, despite original text not having a space

**To reproduce**
1. post a long link
2. as clickable links arent implemented yet, you have to copy and paste the link into your browser
3. notice that link has spaces

**Chatterino version**
Chatterino Nightly 2.1.7 (commit 515657be1, )

**Operating system**
Win 10 2004 19041.329

### PR DESCRIPTION
**Pull request by pajlada**
Pull request checklist:

- [x] `CHANGELOG.md` was updated, if applicable

# Description

To make this work, I've hade to move the color handling out to
IrcMessageBuilder instead of as separate element/container types.

While this does not handle word wrap rendering as well, it does handle
text selection a lot better, and means less duplicate code.

Fixes #1380
Fixes #1865

### CODE REVIEW

**Review by Felanbird — COMMENTED** [review]
Similar to https://github.com/Chatterino/chatterino2/issues/1422#issuecomment-876612890 - links do not work when you are the one who sent them.
See #3203 I'm sure whatever is missing can be copied from there.

**Comment by pajlada** [comment]
> Similar to [#1422 (comment)](https://github.com/Chatterino/chatterino2/issues/1422#issuecomment-876612890) - links do not work when you are the one who sent them. See #3203 I'm sure whatever is missing can be copied from there.

Won't be fixed in this PR. Colors also didn't work for messages that you yourself sent.

Needs to be an overhaul in how we handle non-Twitch IRC, either by parsing client-sent messages differently or using the IRC ECHO feature (or whatever it's called) where possible.

**Comment by Robinlemon** [comment]
very cool

**Review by Mm2PL — APPROVED** [review]

**Comment by zneix** [comment]
very useful feature to have fixed, I'm a big fan of this PR! 🚀
One question though:

> While this does not handle word wrap rendering as well

Does this mean that links that aren't in just one line (wrapped and split onto multiple lines of the same message) will be broken / not considered as a link element and, just like it used to be before, split in half as the line splits?
That's one thing I find confusing. After short code review it looks OK, will have a proper look later though, so don't merge this yet.

**Comment by Mm2PL** [comment]
> Does this mean that links that aren't in just one line (wrapped and split onto multiple lines of the same message) will be broken / not considered as a link element and, just like it used to be before, split in half as the line splits?

Nope, it's still one element


I believe that is referring to an issue similar to #2757 but with just IRC colors

**Comment by pajlada** [comment]
Video of the wrapping I was referring to: https://i.nuuls.com/-1WKT.mp4

This will be fixed with the the "comma after highlighted message" issue.

I'll be daily driving this PR for up to a week so no rush to give feedback

**Comment by pajlada** [comment]
Been using this for a week now without any issues, works great! You're free to merge this when you've had a look at it @zneix

**Comment by zneix** [comment]
While this does good job for normal messages, link parsing in NOTICE messages and possibly some other messages (at least other than PRIVMSG) are still broken:
lol
it's nothing major though and possibly not a blocker, but something that can be further enhanced in the future PR.

**Comment by pajlada** [comment]
Correct, not a blocker. If someone needs it they can create a PR or issue

**Review by zneix — APPROVED** [review]
Didn't find anything bad after a brief review :+1:

**Review by Felanbird — APPROVED** [review]

**Pull request merged**
