### PR TITLE
cleanup output in release builds

### PR DESCRIPTION
**Pull request by swills**
Cleans up debugging output in release builds

### CODE REVIEW

**Comment by fourtf** [comment]
Are any of the `qDebug()` logs useful for running in release mode? Then I would suggest moving them to `qInfo()` and `qWarning()` instead.

**Comment by swills** [comment]
> Are any of the `qDebug()` logs useful for running in release mode? Then I would suggest moving them to `qInfo()` and `qWarning()` instead.

Not that I've seen. Are there any you had in mind?

If category based logging (`qCDebug`, `qCInfo`, `qCWarning`) were used, they could be enabled dynamically at run time. I might look at that, but it's a bigger effort.

**Comment by fourtf** [comment]
> they could be enabled dynamically at run time

I don't think that's necessary but every once in a while I see people looking for logs but most of the things we log right now would probably not be of much use.

**Comment by pajlada** [comment]
@swills I pushed some changes to your branch - could you take a peek and see if those make sense?

If everything looks good, please make the branch up-to-date with master and I'll merge this in :ok_hand:

**Comment by swills** [comment]
Merging done

**Comment by pajlada** [comment]
Closing in favour of #2206

**Pull request closed without merging**
