### PR TITLE
Fixed Usercard Popup not floating on tiling WMs on Linux

### PR DESCRIPTION
**Pull request by qooq69**
Pull request checklist:

- [x] `CHANGELOG.md` was updated, if applicable

# Description
Fixes an issue on i3wm where the Usercard Popup is not floating when `Automatically close usercard popup when it loses focus` setting is enabled.
Tested on i3wm where it fixes the issue, and on KDE with seemingly no change in behavior.
Probably needs testing on other tiling Linux WMs.

### CODE REVIEW

**Comment by pajlada** [comment]
Works as expected for me on i3 - I never noticed this was an issue since I have `for_window [class="chatterino"] floating enable` configured.

If possible, I'd like you to test this on your i3 setup & on KDE before I have this merged in.
I will test this on sway to make sure it doesn't make the experience worse.

**Comment by pajlada** [comment]
@qooq69 Are you able to test this again on your system?

Open for anyone else: Please try this PR on sway to see if it changes the usercard popup experience at all

**Comment by qooq69** [comment]
Sorry for late reply.  Lately I have been busy with uni and real life. Hopefully I'll be able to find some time this weekend to test it on both i3 and sway.

**Comment by qooq69** [comment]
Okay, I have tested it on both i3 and sway. It appears to work without any problems on my machine. 

Also, I'm unable to test it on KDE since I no longer use it, so someone else will have to test it there.

**Review by pajlada — APPROVED** [review]
Let's assume it works as expected then!

**Comment by Felanbird** [comment]
I was on this PR and didn't notice anything unexpected, but I also don't open that many usercards.

**Pull request merged**
