### PR TITLE
Mark big strong contributors as Collaborators

### PR DESCRIPTION
**Pull request by Felanbird**
Pull request checklist:

- [x] `CHANGELOG.md` was updated, if applicable

# Description

In an attempt to highlight people who keep this application going, mm2pl and I discussed bumping each-other to Collaborator(s).

This prompted me to include those who are currently active Contributors who have contributed a lot, and who have added themselves to this list prior.

If you are a contributor who has not yet added themselves to the list, but would likely fall under the Collaborator label, open a PR as normal and I'll bump you in that PR

If you see this PR in the future and are a former-active contributor who has contributed a lot and would like to be bumped, open a PR and I'll approve+merge it.

image

### CODE REVIEW

**Comment by Felanbird** [comment]
@dnsge You get to be the one person I ping on Github, as you are a still-active contributor but not very active in chat

Would you like to be bumped to Collaborator? (feel free to say no if you don't want to, it's not an issue at all 🙂)

**Comment by Wissididom** [comment]
Just one thing I noticed and think would be better for the PR title
```diff
- Collaberators
+ Collaborators
```

**Comment by Felanbird** [comment]
I'll fix on merge with REFINED GITHUB

**Comment by Felanbird** [comment]
@kornes It's come to my attention that you were never given the copy pasta so I'll ping you in this, would you like to be added to the contributors list? As you'd fall under the bump-to-collaborator 🙂

**Comment by kornes** [comment]
> @kornes It's come to my attention that you were never given the copy pasta so I'll ping you in this, would you like to be added to the contributors list? As you'd fall under the bump-to-collaborator 🙂

fine with me, just text without avatar

**Review by pajlada — APPROVED** [review]
Looks good to me!
image

**Review by zneix — APPROVED** [review]
It's was a bit rouge, selfish move from me to move myself to top randomly, good that you are more thoughtful about others that I've been in the past. Respect.

**Comment by Felanbird** [comment]
@Wissididom [2023-01-16 13:28:35] #pajlada pajlada: $notify wissididom you can add yourself to contributors in a PR btw, idk if I posted the copypasta in any of your PRs

**Comment by Wissididom** [comment]
You didn't but I also wasn't sure if I should because I only contributed to things outside of the program code. Will do later I think.

**Pull request merged**
