### PR TITLE
Include reply mention when logging

### LINKED ISSUE #4419: Include normally-stripped mention in replies in logs
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

When a reply to a message gets logged, only the body contents of the message is logged, meaning the context that it was a reply to a specific user is lost.

For example, the following chat:
```
UserA: Foobar!
┌ Replying to @UserA: Foobar!
UserB: Baz!
```
when logged becomes:
```
[00:00:00]  UserA: Foobar!
[00:00:00]  UserB: Baz!
```

---

My proposed solution is to do what both the Twitch mobile app and VOD player do, which is to prefix the message body with the @ mention of the user being replied to.

For example, the following chat:
```
UserA: Foobar!
┌ Replying to @UserA: Foobar!
UserB: Baz!
```
when logged would become:
```
[00:00:00]  UserA: Foobar!
[00:00:00]  UserB: @UserA Baz!
```

### Screenshots

In chatterino:
image

Currently logged:
image

Proposed solution:
image

VOD player:
image

### OS and Chatterino Version

Chatterino 2.4.1 (commit 5ed4a21d) built with Qt 5.15.2, Windows SDK, MSVC 193431942, Crashpad Running on Windows 10 Version 2009, kernel: 10.0.19045

### PR DESCRIPTION
**Pull request by ScrubN**
Pull request checklist:

- [x] `CHANGELOG.md` was updated, if applicable

# Description

Fixes reply mentions getting stripped from logging:

In chatterino:
image

Currently logged (2.4.1):
image

Now logged (PR):
image

Closes #4419

### CODE REVIEW

**Comment by Felanbird** [comment]
Needs to handle when replies are disabled, when the setting is disabled there are two `@replies` since the first one wasn't stripped.
image

**Comment by ScrubN** [comment]
I tested with all combinations of reply stripping and hide reply context and can confirm it no longer produces duplicate mentions in the log.

**Review by Felanbird — APPROVED** [review]
Functionality now works as expected 👍 

image

**Comment by Felanbird** [comment]
I did the merge manually since the workflows would have failed without https://github.com/Chatterino/chatterino2/pull/4427 but I was hoping doing so would allow your changes to auto-trigger workflows, since someone with write-permissions had committed directly, but I guess not 🤔

**Review by pajlada — APPROVED** [review]

**Comment by Felanbird** [comment]
Thanks for your contribution! As a first-time contributor, you can now add yourself to the contributors list that's shown inside the application.

To do so, open a new PR where you modify the contributors.txt file and add yourself to the list. Make sure to read the comments at a top for instructions.

**Pull request merged**
