### PR TITLE
Changelog crash fix (macOS)

### PR DESCRIPTION
**Pull request by dnsge**
Pull request checklist:

- [x] `CHANGELOG.md` was updated, if applicable

# Description

On macOS, trying to display a dialog before showing the main window (like when starting minimized) leads to a crash. The dialog will now show before the main window is opened, preventing this issue.

As far as I know, this issue only existed on macOS.

### CODE REVIEW

**Comment by alazymeme** [comment]
@gempir pong could you pls test this?

**Comment by dnsge** [comment]
Thought I'd add some steps to replicate:

1. In `window-layout.json`: Add the property `"state": "minimized"` to the main window.
2. In `settings.json`: Change the value of `"misc" -> "currentVersion"` to something obviously old, i.e. `"1.0.0"` to prompt the changelog popup. 
3. Start Chatterino

Chatterino will briefly appear before being minimized into the dock. Upon clicking to maximize the window, observe the crash.

**Comment by gempir** [comment]
@alazymeme I'll check it out when I have time

**Comment by gempir** [comment]
The artifact isn't coming, I don't wanna setup the mac build env again.

**Comment by alazymeme** [comment]
@dnsge You should have an option to re-run the checks, can you look for that option [here](https://github.com/Chatterino/chatterino2/pull/1935/checks)?

**Comment by dnsge** [comment]
@alazymeme I couldn't find a place to re-run the checks so I just amended and force pushed. The build actually worked this time.

**Comment by gempir** [comment]
latest nightly cbcd5f3863b6edf22b6d6ffb625bd338f3ea112d crashes and this PR does not! So LGTM 👍 

Tested on macOS Catalina 10.15.6

**Review by pajlada — APPROVED** [review]
:+1:

**Comment by pajlada** [comment]
Thank you for the contribution @dnsge and for double testing it @gempir

**Pull request merged**
