### PR TITLE
Add Mm2PL's avatar to contributors list.

### PR DESCRIPTION
**Pull request by Mm2PL**
Pull request checklist:

- ~~[ ] `CHANGELOG.md` was updated, if applicable~~ N/A

very simple PR, title
See #2126

### CODE REVIEW

**Comment by 23rd** [comment]
Why it can't be made with shorten Github avatar links?
For example: https://github.com/Mm2PL.png.

**Comment by pajlada** [comment]
> Why it can't be made with shorten Github avatar links?
> For example: https://github.com/Mm2PL.png.

That removes our final say whether the contents of an avatar fits in the about page or not in case the user of a previously approved avatar updates their avatar.

**Comment by leon-richardt** [comment]
> Why it can't be made with shorten Github avatar links?
> For example: https://github.com/Mm2PL.png.

Another point: not everyone might want their avatar to be embedded in the app.

**Comment by Mm2PL** [comment]
> Why it can't be made with shorten Github avatar links?
> For example: https://github.com/Mm2PL.png.
What if someone changes their username on github. It's just easier to include avatars as images.

**Comment by 23rd** [comment]
> That removes our final say whether the contents of an avatar fits in the about page or not in case the user of a previously approved avatar updates their avatar.

Okay, understood. 👌

> Another point: not everyone might want their avatar to be embedded in the app.

This could be solved with a tag, e.g. `[avatar]`.

> What if someone changes their username on github.

Then the link to his/her account will be invalid as well.

**Pull request merged**
