### PR TITLE
Chat commands api

### PR DESCRIPTION
**Pull request by 158flairincident**
add a way to remove grey messages like the refresh emotes messages
chat2

### CODE REVIEW

**Comment by sando** [comment]
Nor sure what you're trying to achieve with this PR. Feature requests belong here: https://github.com/Chatterino/chatterino2/discussions

**Comment by Mm2PL** [comment]
Why was this closed?

11 kwi 2022 03:04:32 Felanbird ***@***.***>:

**Comment by Felanbird** [comment]
> Why was this closed? 

It's a PR that commits the branch `chat-commands-api` into the branch `chore/archlinux-nightly-ci` that has the description of a feature request.

**Comment by Mm2PL** [comment]
Oh I got confused, I thought this was fourtf's chat commands pr

11 kwi 2022 10:08:18 Felanbird ***@***.***>:

**Pull request closed without merging**
