### PR TITLE
Release v2.4.6

### PR DESCRIPTION
**Pull request by pajlada**
# Description

This PR aims to prepare a new release of Chatterino which only updates the version of Qt used for the main Windows build.
This build is based on the v2.4.5 release since the changes in master right now are not considered stable.

I want to merge this into the `bugfix-release/v2.4.6` branch, but since it's not a protected branch CI jobs won't run, so I'll target that branch after CI has built and testing has been done

This PR has removed Qt5 builds.

# Checklist for making a release

## In the release PR

- [x] Updated version code in `src/common/Version.hpp`
- [x] Updated version code in `CMakeLists.txt`  
       This can only be "whole versions", so if you're releasing `2.4.0-beta` you'll need to condense it to `2.4.0`
- [x] Add a new release at the top of of the `releases` key in `resources/com.chatterino.chatterino.appdata.xml`  
       This cannot use dash to denote a pre-release identifier, you have to use a tilde instead.

- [x] Updated version code in `.CI/chatterino-installer.iss`
- [x] Update the changelog `## Unreleased` section to the new version `CHANGELOG.md`  
       Make sure to leave the `## Unreleased` line unchanged for easier merges

## After the PR has been merged

- [ ] Tag the release
- [ ] Manually run the [create-installer](https://github.com/Chatterino/chatterino2/actions/workflows/create-installer.yml) workflow.  
       This is only necessary if the tag was created after the CI in the main branch finished.
- [ ] ~~Start a manual [Launchpad import](https://code.launchpad.net/~pajlada/chatterino/+git/chatterino) - scroll down & click Import Now~~  
       **Not necessary as the PPA build uses system qtimageformats plugins, which have been patched in Ubuntu**

 - [ ] ~~Make a PPA release to [this repo](https://git.launchpad.net/~pajlada/+git/chatterino-packaging/) with the `debchange` command.  
       `debchange -v 2.4.0` then add the changelog entries  
       `debchange --release` then change the distro to be `unstable`~~
       **Not necessary as the PPA build uses system qtimageformats plugins, which have been patched in Ubuntu**

### CODE REVIEW

**Review by Mm2PL — APPROVED** [review]

**Review by Felanbird — APPROVED** [review]

**Comment by pajlada** [comment]
Test installer for windows users: https://github.com/Chatterino/chatterino2/suites/16675090642/artifacts/952854026

**Comment by pajlada** [comment]
New installer posted in the above comment

**Comment by Felanbird** [comment]
issues from qt6.5.3 are resolved on this new installer as expected

**Comment by pajlada** [comment]
Closing this as this PR was more for gathering comments about the changes

**Pull request closed without merging**
