### PR TITLE
chore: use system logical core count for Ubuntu/macOS builds

### PR DESCRIPTION
**Pull request by jammehcow**
Pull request checklist:

- [x] `CHANGELOG.md` was updated, if applicable

# Description

This PR aims to replace the hardcoded `-j8` make flag with a logical core count lookup. 

Ubuntu uses nproc (available on Linux), whereas macOS has to use a sysctl call. Could also use `getconf _NPROCESSORS_ONLN` as it returns the same result on both platforms.

### CODE REVIEW

**Comment by jammehcow** [comment]
Note: Windows already sets an envvar to max out job count, no change needed.

**Comment by Mm2PL** [comment]
Shouldn't just `make -j` work?

**Comment by jammehcow** [comment]
> Shouldn't just `make -j` work?

image
Will leave it as is :)

**Comment by Mm2PL** [comment]
Yeah don't use -j, make spawned so many processes my X and PulseAudio stopped responding lol

**Review by pajlada — APPROVED** [review]

**Pull request merged**
