### PR TITLE
Add chocolatey badge + information to the readme

### PR DESCRIPTION
**Pull request by alazymeme**
Pull request checklist:

- [x] `CHANGELOG.md` was updated, if applicable

# Description

This pr adds the chocolatey badge on the readme

### CODE REVIEW

**Comment by cinemassacres** [comment]
Closes #1981

**Comment by alazymeme** [comment]
NOIDONTTHINKSO

**Comment by alazymeme** [comment]
Package approved: https://chocolatey.org/packages/chatterino

**Comment by fourtf** [comment]
Looks good to me :+1:

**Pull request merged**
