### PR TITLE
Usercards no longer close when the originating window (e.g. a search popup) is closed

### LINKED ISSUE #2297: Clicking on username hyperlink in UserInfoPopup no longer works
**Describe the bug**
In earlier builds, clicking username hyperlinks in UserInfoPopup recent messages used to bring up another UserInfoPopup for the user in question. This was helpful for following a conversation. It appears this functionality broke recently in 1ee1e8837f82cafb56fbffa1e4fe83dc2e41bced, but works fine in 523874dc210e41640986299d0b07c0fa6c6e76de.

**To reproduce**
1. *Automatically close user popup when it loses focus* option is enabled 
2. Open a UserInfoPopup
3. Click on a mentioned user in their recent messages
4. The first UserInfoPopup disappears, and a second one doesn't appear at all

**Screenshots**
Behaviour when working (523874dc210e41640986299d0b07c0fa6c6e76de):
YHUPGjTgCf
Behaviour when broken (1ee1e8837f82cafb56fbffa1e4fe83dc2e41bced):
yt99fFLVTM

**Chatterino version**
Chatterino Nightly 2.2.3-beta2 (commit fea52faa6, 19.12.2020)

**Operating system**
Windows 10 20H2 (OS Build 10942.662)

### LINKED ISSUE #3512: Closing the search popup also closes usercards opened from the popup
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

When opening usercards from the search popup (default keybinding: Ctrl+F), the usercards will close as soon as the search popup is closed. I do not consider this expected and/or desired behavior and I would like to stay them open until explicitly closed.

### OS and Chatterino Version

Linux balerion 5.16.0-arch1-1, 82009982

### PR DESCRIPTION
**Pull request by qooq69**
Pull request checklist:

- [x] `CHANGELOG.md` was updated, if applicable

# Description
Fixes #2297
Fixes #3512

Not sure if this PR changes intended way the usercard popups are supposed to behave.
What's interesting is that it was never an issue on MacOS since they always had MainWIndow as parent.
This PR makes usercard popups behave the same way on all opearting systems.

### CODE REVIEW

**Comment by pajlada** [comment]
Behaviour change in i3: Closing the Search Popup now closes all User Info Popups that were opened from the Search Popup, which is fine by me.

**Comment by pajlada** [comment]
Also works well with latest main branch commit

**Comment by pajlada** [comment]
Confirmed it fixes #2297 too

**Comment by ilyazzz** [comment]
Seems to work properly on sway/wayland.

**Review by Felanbird — APPROVED** [review]
Works on Windows - `automatically close user popup with it loses focus` disabled in screenshot
image

**Review by pajlada — APPROVED** [review]
:+1:

**Review by zneix — APPROVED** [review]

**Pull request merged**
