### PR TITLE
Add a function in NetworkCommon `parseHeaderList` which parses a header list as a string into a vector of header pairs

### PR DESCRIPTION
**Pull request by pajlada**
Pull request checklist:

- [x] `CHANGELOG.md` was updated, if applicable

# Description

### CODE REVIEW

**Comment by Bun** [comment]
The code suggests colons are not allowed in the header values, but [RFC7230 section 3.2](https://tools.ietf.org/html/rfc7230#section-3.2) suggests otherwise. This would prevent e.g. authorization tokens that use `:` somewhere.

**Comment by pajlada** [comment]
> The code suggests colons are not allowed in the header values, but [RFC7230 section 3.2](https://tools.ietf.org/html/rfc7230#section-3.2) suggests otherwise. This would prevent e.g. authorization tokens that use `:` somewhere.

Thanks for the heads up - I'll modify the code and add some tests for it

**Comment by pajlada** [comment]
> The code suggests colons are not allowed in the header valu

I believe the latest commit remedies this, the limitation I've put on this now instead is that the value, after trimming, must not be empty.
So `Authorization:` is invalid

**Comment by pajlada** [comment]
Code ready for review now, if you could take another peek @Bun that'd be great in addition to :snake: 's eyes :eyes:

**Review by zneix — APPROVED** [review]
No idea why did I put off this review, good stuff :+1:

**Comment by pajlada** [comment]
Will update branch and merge this one in after #2634

**Pull request merged**
