### PR TITLE
Elevated messages removed

### PR DESCRIPTION
**Pull request by killertofus**
Pull request checklist:

- [x] `CHANGELOG.md` was updated, if applicable

# Description

### CODE REVIEW

**Comment by Felanbird** [comment]
Do you have any confirmation the experiment is over? While it might not be running currently it could easily just appear again

**Comment by Felanbird** [comment]
We can look at removing Elevated Messages once we get some confirmation they aren't coming back, currently the help page is still live.

**Comment by killertofus** [comment]
@Felanbird https://twitter.com/TwitchSupport/status/1722675472218141072

**Comment by pajlada** [comment]
Let's wait a little bit more to see what they do with bits and what-not

**Pull request closed without merging**
