### PR TITLE
Fixed switching tabs using trackpad scroll.

### PR DESCRIPTION
**Pull request by 23rd**
Unfortunately, my implementation of the switching tabs with the scroll is useless for the Mac users with the trackpad. =(
So this PR fixes it.

[i.imgur.com/GQtSFFZ.mp4](https://i.imgur.com/GQtSFFZ.mp4)

### CODE REVIEW

**Comment by pajlada** [comment]
High risk change, I will want to try this out properly before merging it

**Comment by 23rd** [comment]
No problem.
120 units was taken from [Qt documentation](https://doc.qt.io/qt-5/qwheelevent.html#angleDelta).

**Comment by fourtf** [comment]
Please use `this->` when accessing members.

**Comment by pajlada** [comment]
Merging so its built on all platforms so I can more easily test it on all platforms.

**Pull request merged**
