### PR TITLE
Add missing tab completion for commands

### PR DESCRIPTION
**Pull request by Mm2PL**
# Description

adds completion for `/usercard`, `/follow`, `/unfollow`, `/ignore`, `/unignore`

### CODE REVIEW

**Comment by zneix** [comment]
Since this adds autocompletion for a command, should autocompletion for `/follow` be added as well?

**Comment by Mm2PL** [comment]
I can make a new PR or make this one add tab completion to other commands. However if we'd go with making a new one then this would need to be merged before i start it, otherwise there would be merge conflicts.

**Comment by zneix** [comment]
I think you can just add second command to this PR and change the title. Having to deal with merge conflicts isn't worth it imo.

**Comment by Mm2PL** [comment]
`/follow`, `/unfollow`, `/ignore`, `/unignore` as missing tab-completion aswell

**Comment by zneix** [comment]
Great catch :+1: I missed the rest of them.

**Pull request merged**
