### PR TITLE
Migrate /announce command to Helix API.

### PR DESCRIPTION
**Pull request by Mm2PL**
Pull request checklist:

- [x] `CHANGELOG.md` was updated, if applicable

# Description

### CODE REVIEW

**Comment by Wissididom** [comment]
Idk if it is important, but shouldn't `Helix::sendChatAnnoucement` rather be `Helix::sendChatAnnouncement` (missing n in Announcement)

**Comment by Felanbird** [comment]
Can we implement colored announcements in this PR? I believe the only real disdain against them was the fact that IRC invoked announcements did not return color data, which is "resolved" by their deprecation.

**Comment by Mm2PL** [comment]
> Idk if it is important, but shouldn't Helix::sendChatAnnoucement rather be Helix::sendChatAnnouncement (missing n in Announcement)

fixed

**Comment by Mm2PL** [comment]
> Can we implement colored announcements in this PR (maybe just the commands)? I believe the only real disdain against them was the fact that IRC invoked announcements did not return color data, which is "resolved" by their deprecation.

I decided to introduce internal support for sending colored announcements as it was simply more effort to not do it. I didn't want to do commands because I wanted the PR to only move the existing command to helix, just fix the 'bug' and not introduce any new features at the same time. :)

**Review by pajlada — APPROVED** [review]
:+1: Looks good to me!
Letting you hit the Merge button so you have an opportunity to complain about the changes I've made @Mm2PL

**Comment by Mm2PL** [comment]
ibana.pjg

**Pull request merged**
