### PR TITLE
fix: resolve /live channel liveness using their channel ID

### LINKED ISSUE #5158: `/live` channels never resolve when the channel was populated before displayname casing could be obtained
The `/live` tab uses display name casing, which is fair since we use it to populate the tab name as well.

The problem is the `/live` tab will sometimes populate the channels before the displayname casing is loaded, and due to this the channel will never gray out.

image
These are the `/live` tabs for me from 2024-1-28, the ones that did not get displayname casing never resolved themselves.

Probably could be fixed by just accepting case-insensitive resolving, if we're watching `bobross` but `BobRoss` goes offline, that's good enough.

### PR DESCRIPTION
**Pull request by KleberPF**
This fix for #5158 uses the `TwitchChannel` `roomId()` as the message id when sending live messages (`TwitchMessageBuilder::liveMessage` and `TwitchMessageBuilder::liveSystemMessage`). I wasn't able to replicate the same logic for live messages sent through `NotificationController` (I couldn't find a way to access the `TwitchChannel` from there), so I went with the other option of using a case insensitive string compare. I accept any ideas on how I could do this better, especially the `NotificationController` bit.

(felanbird): Fixes #5158

### CODE REVIEW

**Comment by Felanbird** [comment]
changelog.md entry
```- Bugfix: Fixed an issue where channels who were live before you opened Chatterino didn't always get greyedout in the `/live` tab when they went offline (#5172)```

**Review by Felanbird — APPROVED** [review]
This seems to work as expected, so far 3 of my channels loaded before displayName capitalization was obtained, have correctly been greyed-out in the `/live` tab when they went offline

**Comment by KleberPF** [comment]
Thanks for the review. Should I add a commit with the changelog entry?

**Comment by Felanbird** [comment]
> Thanks for the review. Should I add a commit with the changelog entry?

if you want, otherwise pajlada will do it on the weekend (and maybe move my comma)

**Review by pajlada — APPROVED** [review]
Little bit hard to test but it seems to work as expected - thank you!

**Comment by pajlada** [comment]
Thank you! As a first-time contributor, you can now add yourself to the contributors list that's shown inside the About page in Chatterino.

If you want this, you can open a new PR where you modify the `resources/contributors.txt` file and add yourself to the list. Make sure to read the comments at the top for instructions.

**Pull request merged**
