### PR TITLE
📦 Create appimage

### PR DESCRIPTION
**Pull request by AnotherFoxGuy**
Travis will now use [linuxdeployqt](https://github.com/probonopd/linuxdeployqt) to build and deploy an [AppImage](https://appimage.org/) for Linux

### CODE REVIEW

**Comment by pajlada** [comment]
Thank you! Looking forward to trying this out

**Comment by pajlada** [comment]
ah, ubuntu bionic (18.04 LTS) doesn't have the required Qt version installed. we need Qt 5.10 at least

**Comment by pajlada** [comment]
If you're able to use a custom docker image, we have an 18.04 docker image that installs a newer version of Qt

**Comment by AnotherFoxGuy** [comment]
Bionic has QT 5.9

**Comment by AnotherFoxGuy** [comment]
But I could try to use https://launchpad.net/~beineri/+archive/ubuntu/opt-qt-5.12.0-bionic

**Comment by pajlada** [comment]
sure, try it out

**Comment by AnotherFoxGuy** [comment]
The Linux build has been fixed now

**Comment by pajlada** [comment]
Looks great, thank you very much!

**Pull request merged**
