### PR TITLE
Remove "needs triage" issue label

### PR DESCRIPTION
**Pull request by RAnders00**
Pull request checklist:

- [x] `CHANGELOG.md` was updated, if applicable

# Description

Also, delete the label for existing issues here: https://github.com/Chatterino/chatterino2/issues/labels

### CODE REVIEW

**Comment by alazymeme** [comment]
Are there any bots that would automatically remove the label if people are able to reproduce the issue perhaps?

**Comment by Mm2PL** [comment]
I am a bit OOTL. Why is the "needs triage" label going?

**Comment by alazymeme** [comment]
> I am a bit OOTL. Why is the "needs triage" label going?

image

**Comment by alazymeme** [comment]
There's some bots that will remove the triage label when you add another tag to it, but once again that relies on an admin/mod actively sorting through the issues. pajlada has too many issues to look at - which is why he doesn't get to them. fourtf is usually busy with work or something else. wShrug

**Comment by RAnders00** [comment]
The idea for the "needs triage" labels originally came from me. Here is my original PR introducing them: https://github.com/Chatterino/chatterino2/pull/1214

**Review by pajlada — APPROVED** [review]

**Pull request merged**
