### PR TITLE
feat: improve @Mm2PL's CI splitting work

### PR DESCRIPTION
**Pull request by jammehcow**
Pull request checklist:

- [ ] `CHANGELOG.md` was updated, if applicable

# Description

This PR aims to update @Mm2PL's CI splitting work directly onto his branch :)

PR into the PR

### CODE REVIEW

**Comment by jammehcow** [comment]
Don't it look pretty? 
image

**Comment by Felanbird** [comment]
> Don't it look pretty? 

wow~

**Comment by ALazyMeme** [comment]
Jesus this commit history is worse than one of my prs

**Comment by Felanbird** [comment]
> Jesus this commit history is worse than one of my prs

he forgot to soft reset and re-commit the diff as a single commit 🧍‍♂️ 🕯️

**Comment by jammehcow** [comment]
I just merged in master as a single commit. GH shows all commits from that? Odd.

**Review by Mm2PL — APPROVED** [review]
yolo

**Comment by xHeaveny** [comment]
> yolo

oka or just like this xd

**Pull request merged**
