### PR TITLE
fix: QuickSwitcherPopup now pops up in the selected window

### PR DESCRIPTION
**Pull request by pajlada**
# Description

- fix: QuickSwitcherPopup now pops up in the selected window
- QuickSwitcherPopup: reduce indentation anon namespace
- QuickSwitcherPopup: constexpr the minimum size
- QuickSwitcherPopup: remove redundant virtual from `themeChangedEvent`

### CODE REVIEW

**Comment by pajlada** [comment]
@Mm2PL I removed one of the questionable usages of `getMainWindow`, could you take a look at this PR? Only the first commit makes actual behavioral changes

Related to https://github.com/Chatterino/chatterino2/pull/4816

**Review by Mm2PL — CHANGES_REQUESTED** [review]
Opening a new channel in a tab still uses the main window. Can you fix that? It is located in `src/widgets/dialogs/switcher/NewTabItem.cpp`.

**Comment by pajlada** [comment]
> Opening a new channel in a tab still uses the main window. Can you fix that? It is located in `src/widgets/dialogs/switcher/NewTabItem.cpp`.

[`2b75961` (#4819)](https://github.com/Chatterino/chatterino2/pull/4819/commits/2b75961d44656b1bf990ac961173876e0eea81ec) should fix this. I have tested it but would be good with a sanity check. Good catch!

**Review by Mm2PL — APPROVED** [review]
Yep works as expected now.

**Pull request merged**
