### PR TITLE
Discord-like Quick Switcher

### PR DESCRIPTION
**Pull request by leon-richardt**
### Description
This PR aims to implement a Discord-style quick switcher/navigator, as suggested in #1485.

### TODO List
- [x] Switch to a split containing the searched channel
- [x] Open a new split with the searched channel
- [x] Make usable with mouse
- [x] Make sure popup always spawns in a sensible location
- [x] Allow searching for tab titles, not just split titles
- [x] Add in-source documentation
- [x] (?) Nice UI
- [x] Add changelog entry
- [x] ~Add latest whisper as a navigation option (cf. https://github.com/Chatterino/chatterino2/pull/1588#issuecomment-593573988)~ (scrapped for now)

Feel free to request additional features. :)

### Screenshots
<details>
  <summary>Screenshots</summary>

Current state of UI
</details>

### CODE REVIEW

**Comment by Mm2PL** [comment]
Is it possible to have the latest whisper displayed at the top when nothing is in the box? My idea is that clicking on that option would go to a `/whispers` tab and type the equivalent of `/r`

**Comment by Mm2PL** [comment]
Found a crash, pressing `TAB` in the box without any possible options to pick causes a crash via a `SIGFPE`
My OS is `Linux` :)

**Comment by leon-richardt** [comment]
> Found a crash

Thanks for finding that, fixed in 187ee09.

**Comment by Mm2PL** [comment]
Opening a new split crashes for me FeelsBadMan i will try to get a debugger attached :)

**Comment by leon-richardt** [comment]
> Opening a new split crashes for me FeelsBadMan i will try to get a debugger attached :)

Don't bother, that's not implemented yet. 😅

**Comment by Mm2PL** [comment]
oh okay :)

**Comment by Mm2PL** [comment]
I have another idea. Can we have the name of the notebook tab shown in the quick switcher, almost like Discord does it?

**Comment by leon-richardt** [comment]
I think the PR is ready for review now.

Note that I slightly changed an existing interface: `SplitContainer::setSelected(Split *)` is now `public`. I don't think this leads to problems anywhere but I guess it could be changed if there are objections against this.

Also note that I scrapped the idea to display the latest whisper for now; I didn't feel comfortable with my implementation. This might get revisited at a later point.

I'm happy to address any review comments.

**Comment by fourtf** [comment]
doesn't work with dark mode and icons look like shit, will merge

**Comment by leon-richardt** [comment]
> doesn't work with dark mode and icons look like shit, will merge

I assume you mean light/white mode?

Yeah, feel free to replace icons with anything you find more fit.

**Pull request merged**
