### PR TITLE
Update QualityPopup.hpp

### PR DESCRIPTION
**Pull request by Danis-Enikeev**
Now this window automatically goes in floating mode in dwm (not sure if it works for i3 though).

### CODE REVIEW

**Comment by Mm2PL** [comment]
There seems to be a BasePopup class, maybe you could use that instead of QPopup.

**Comment by Danis-Enikeev** [comment]
Tried the BasePopup with `setWindowFlags(Qt::Dialog)` but it didn't produce the desired result. It might be a good idea to rewrite the BasePopup class so it inherits from something QDialog based instead of BaseWindow.

**Comment by pajlada** [comment]
Closing in favour of #1843

**Comment by pajlada** [comment]
@Danis-Enikeev #1843 is being merged into master now - thanks for making me look into it!

**Pull request closed without merging**
