### PR TITLE
Add issue forms

### PR DESCRIPTION
**Pull request by Mm2PL**
Pull request checklist:

- [x] ~~`CHANGELOG.md` was updated, if applicable~~ not applicable.

# Description

No more badly formatted or empty issues! :tada: 

You can see this in action on https://github.com/mm2pl/testingxdd/issues/new/choose

### CODE REVIEW

**Review by Felanbird — APPROVED** [review]
cool

**Comment by Mm2PL** [comment]
Gonna add checkboxes kinda like the yt_dlp project has :)

**Review by zneix — APPROVED** [review]
LGTM

**Review by pajlada — APPROVED** [review]

**Comment by Felanbird** [comment]
I'm gonna merge this normally because pajlada is busy with rust - ci hours 📈

**Pull request merged**
