### PR TITLE
Enable/disable highlights on a per-channel basis

### LINKED ISSUE #2365: Highlights for specific channels.
What should be added?
Highlights for specific channels.

Why should it be added?
I wan't a specific emote to be highlighted, but it get's spammed a lot in some other channels.

Example:
billede
billede

### PR DESCRIPTION
**Pull request by jammehcow**
Pull request checklist:

- [ ] `CHANGELOG.md` was updated, if applicable

# Description

This PR aims to allow the enabling/disabling of custom highlights on a channel by channel basis. A dialog should be added from the split menu that has enable/disable checkboxes for each highlight. Highlights should also be enabled/disabled globally by default (when the user hasn't already disabled in a channel) from the main highlights page.

TODO:
 - [x] Add flag to highlight settings for global visibility
 - [x] Add underlying IDs to highlights for lookup
 - [ ] Add section to window layout for disabled split highlights ~*OR* to highlight settings with a list of disabled channels~
 - [ ] Create menu item in split header menu
   - Need to disable for /whispers & /mentions 
 - [ ] Create dialog for disabling/enabling in a split

Fixes #2365 and speaks to #2354

### CODE REVIEW

**Comment by jammehcow** [comment]
For this to work across the settings file (highlight storage) and the window-layout file (splits contain a list of disabled highlights) I'll need to add a unique identifier to each highlight on creation. Also need to support a migration from highlights without an ID to give them one.

**Comment by jammehcow** [comment]
@fourtf could I get your eyes over this please? Idea for the dialog that'll show up when you pres `Toggle Highlights` in the split's right click menu.

https://www.figma.com/file/FqrdvIzhJGbW7vBh8mBXts/c2-2882-Channel-Highlight-Enable-Disable-Dialog

**Comment by jammehcow** [comment]
Abandoning in favour of a potential filter-like highlight system.

**Comment by 2547techno** [comment]
@jupjohn just curious, has the state of the highlight system changed since 2021 to the "potential filter-like highlight system"? I can't remember what it was like in 2021, but from looking at your figma it doesn't seem like it has changed (?)

**Pull request closed without merging**
