### PR TITLE
Add option to display tabs on the right and bottom

### LINKED ISSUE #1930: Vertical Tab Layout on the right
**What should be added?**
I really enjoy the vertical tab layout but I would love for an option to put it on the right side of the chat

**Why should it be added?**
More user customization

### PR DESCRIPTION
**Pull request by dnsge**
# Description

Adds the option to place the notebook tabs on the right and bottom. Also, ignore the incorrect branch name :)

Screen Shot 2022-07-01 at 10 05 53 PM
Screen Shot 2022-07-01 at 10 06 02 PM

Closes #1930
Related to #3601

Pull request checklist:

- [x] `CHANGELOG.md` was updated, if applicable

### CODE REVIEW

**Comment by dnsge** [comment]
I had held off on marking this pull request as ready for review because I wanted to somehow clean up the rendering logic and have some more shared code between each tab location. However, after looking more at the logic I think that making the code shared would make it much more complex for little benefit. So here we are. 

(Ignore my attempts at trying to rename the branch)

**Review by pajlada — COMMENTED** [review]
Minimum tab bar size is too large when Tab layout is set to Bottom



Bottom layout
bottom layout

Top layout (works as expected)
top layout

**Comment by dnsge** [comment]
Fixed the spacing with buttons and tabs hidden in 791ebc6

**Review by pajlada — APPROVED** [review]
Looks good! Thank you

**Pull request merged**
