### PR TITLE
Change the highlight order to prioritize Message highlights over User highlights

### LINKED ISSUE #4259: Message highlights taking priority over user highlights
### Discussed in https://github.com/Chatterino/chatterino2/discussions/3865

<div type='discussions-op-text'>

<sup>Originally posted by **LosFarmosCTL** July 17, 2022</sup>
Was there a specific reason to make user highlights take priority over message/phrase highlights?

IMO it would make more sense the other way around, highlight all messages from one user, but i.e. if that one user pings me I'd still want that to take priority.</div>

`felanbird:`
I'm moving this to an issue, in hopes it gets more traction. Since the release of 2.4.0, the most common deterrent to updating in certain areas of Twitch, is this functionality change. 
Due to the issues with 7.4.0's release, the discussion of updating happens way more often, and due to this, other chatters are able to give their opinion, which is to not update.
I'd say out of every 10 users, 4 of them update, 2 are too lazy, and the other 4 either experienced the change, or were deterred by another who did.

pajlada's comment:
image

### PR DESCRIPTION
**Pull request by pajlada**
Pull request checklist:

- [x] `CHANGELOG.md` was updated, if applicable

# Description

- Change the highlight order to prioritize Message highlights over User highlights
- Add changelog entry

Fixes #4259

### CODE REVIEW

**Review by Felanbird — APPROVED** [review]
See my section of #4259 for my opinion on why I'd like this.

Summary being `If a user you have highlighted, pings you, said message is not highlighted in the ping color, which causes confusion of who pinged you`

**Comment by pajlada** [comment]
:sunglasses: :mega: I'm going to merge this in later today, leave your feedback if you have any

**Comment by 8thony** [comment]
I'm okay with message > user, but we should consider implementing a system so every user can set up the order of the highlights based on their personal preferences. 
for example my case (#4191) is impossible since v2.4.0.
Other users have ideas to make it more customizable like #3472. 
Let me know what you think. 
based on https://github.com/Chatterino/chatterino2/discussions/3872#discussioncomment-4684561

**Comment by Felanbird** [comment]
Obviously it would be preferred to have the custom system, but as far as I'm aware nobody has it in the pipeline, and I would like as little users as possible to feel restricted on update, due to the loss of so much `/command` functionality if they do not update by Feb 18th.
So this approach is best needed as of now.

**Pull request merged**
