### PR TITLE
Ignore out of bounds check on tiling WMs

### PR DESCRIPTION
**Pull request by Ckath**
Pull request checklist:

- [x] `CHANGELOG.md` was updated, if applicable

# Description

I get these every time on dwm I'm sick of seeing the popup, windows dont have a choice where to spawn anyway.

### CODE REVIEW

**Review by pajlada — CHANGES_REQUESTED** [review]
I would prefer a command option instead, so users of tiling window managers can add `--tiling-wm` to their `.desktop` file if desired.

**Comment by Ckath** [comment]
alternatively, is there maybe a way to detect tiling windowmanagers or windows being moved by the wm? I couldnt think of something clear cut right away so went with this

**Comment by pajlada** [comment]
A runtime detection through environment variables or something could also work for sure, yes.

**Comment by pajlada** [comment]
Environment variables set on my system running on Arch Linux btw with i3

```
DESKTOP_STARTUP_ID=i3/st/3037-....
I3SOCK=/run/user/1000/i3/ipc-socket.3037
```

**Comment by Ckath** [comment]
now I just have to set `I3SOCK` but thats fine

**Review by pajlada — APPROVED** [review]

**Comment by pajlada** [comment]
Please wait with fixing the formatting until after https://github.com/Chatterino/chatterino2/pull/3267 has been merged into master, and ensure your branch is then up-to-date with `origin/master` to save on CI hours

**Review by pajlada — APPROVED** [review]

**Pull request merged**
