### PR TITLE
Input completion popup improvements

### PR DESCRIPTION
**Pull request by 0xcc77**
Pull request checklist:

- [x] `CHANGELOG.md` was updated, if applicable

# Description

* inputCompletionPopup used to have a fixed height, now it is resized up to half of the split height, based on it's contents.
* inputCompletionPopup is now positioned properly when window was resized or moved

### CODE REVIEW

**Review by pajlada — CHANGES_REQUESTED** [review]
Add a changelog entry

Known issues: New splits don't have a maximum height set on the input completion popup, probably because a resize event hasn't fired.

**Comment by pajlada** [comment]
Would also love a video showing off the functionality

**Comment by 0xcc77** [comment]
> Would also love a video showing off the functionality

https://i.nuuls.com/JJ0ZU.mp4

**Review by pajlada — CHANGES_REQUESTED** [review]
Test it on Windows, I've had reports of this PR making the Chatterino window unmoveable

**Comment by ALazyMeme** [comment]
Can confirm, this PR makes the window un-moveable.
ComfortableLesserImage

**Pull request closed without merging**
