### PR TITLE
Add Fuzzy Matching to emote input completion

### PR DESCRIPTION
**Pull request by kklixd**
Pull request checklist:

- [x] `CHANGELOG.md` was updated, if applicable

# Description

This change adds Fuzzy Matching to the emote popup when colon (:) is typed in chat.

Example:

Before:
Before

After:
After

### CODE REVIEW

**Comment by Felanbird** [comment]
We have a long discussion about bettering the colon emote menu in #4414 - but I feel like fuzzy search is the exact opposite of what people want.

**Comment by LosFarmosCTL** [comment]
> but I feel like fuzzy search is the exact opposite of what people want.

I think fuzzy matching would be fine as long as it's lower priority than any of the other discussed options.

So an exact match has to always beat fuzzy search, prioritized by the criteria outlined in that discussion and only be at the top when there is no good match. But I think that in general it could be beneficial i.e. if you mistype something.

**Comment by kklixd** [comment]
Sorry for the late reply, but hopefully I have fixed it.

**Comment by pajlada** [comment]
With #4639 merged in, this PR will look pretty different. Please open a new PR if you are still interested in implementing fuzzy matching.

**Pull request closed without merging**
