### PR TITLE
Fix color @usernames sometimes not working at all

### LINKED ISSUE #2822: Color @usernames stopped working
**Describe your issue**
In the recent nightly, **Windows 10, Chatterino Nightly 2.3.2 (commit 3fddafb86, CMAKE)**,
`Color @usernames` setting stopped working.
image

This setting works fine for me on 258851e5729508e7839702ed65ee0d900da00cea.

### PR DESCRIPTION
**Pull request by pajlada**
Pull request checklist:

- [x] `CHANGELOG.md` was updated, if applicable

# Description

Definitely memory fuckery involved - The comment from @lubieerror https://github.com/Chatterino/chatterino2/issues/2822#issuecomment-897252673 is finally what led me to adding tests and hopefully fixing this.

- Add changelog entry
- fix(lrucache): Ensure max_size is maintained in move ctor & operator=
- Add tests for ChannelChatters/chatterColors_

Fixes #2822

### CODE REVIEW

**Comment by pajlada** [comment]
@felanbird @zneix @Mm2PL @talneoran @lubieerror could I have your eyes on this and potentially have you test this out as your daily driver for a while to see if it seems good?

**Comment by Mm2PL** [comment]
I could merge it into Dankerino and revert before merging upstream.

**Review by Mm2PL — APPROVED** [review]
Merged into Dankerino in 62ffbc052207deacbca4e73ea8287a2763ed64a8 :)

**Review by Felanbird — APPROVED** [review]
Functionality works as intended. 👍

Tested this PR by checking it out on Sunday night -> Colored @'s worked.
Kept it open until likely unrelated Qt5Core.dll crash happened on Thursday afternoon, other than that nothing seemed out of the ordinary, and no issues arose while running the PR running.

Re-built, colored @'s continued to work, once again noticed no issues from then until I am writing this approval. 🙂

**Comment by zneix** [comment]
I've noticed Chatterino use noticeably more resources (RAM / CPU) while running Chatterino built from this PR. It may be just my laptop, I'll keep testing this out alternately with master to see if it's actually this PR causing the issues and measure the increase in RAM usage.
For now I just wanted to leave this note here.

**Comment by pajlada** [comment]
> I've noticed Chatterino use noticeably more resources (RAM / CPU) while running Chatterino built from this PR. It may be just my laptop, I'll keep testing this out alternately with master to see if it's actually this PR causing the issues and measure the increase in RAM usage.
> For now I just wanted to leave this note here.

This is to be expected - Chatterino will now, as intended, keep 5000 username colors in memory per channel.

**Comment by somso2e** [comment]
It works perfectly fine. 
Also, I should mention I noticed the RAM usage going up to 900MB compared to my normal 350MB, but I've seen this happen on older builds as well so I can't confirm if it's this PR that is causing this high RAM usage or not.

**Comment by pajlada** [comment]
Memory usage aside, I'm calling this PR a success. Further memory usage tweaks can take place in separate PRs.

Some automated memory usage testing would be great as a CI addition.

**Pull request merged**
