### PR TITLE
Added my profile picture to Contribution List

### PR DESCRIPTION
**Pull request by hicupalot**
Pull request checklist:

- [x] `CHANGELOG.md` was updated, if applicable

# Description

I added my profile picture to the contributors list as I forgot to add it last time

### CODE REVIEW

**Comment by hicupalot** [comment]
I didn't update the changelog as this doesn't need a changelog entry

**Comment by hicupalot** [comment]
> 

Thanks for the help and sorry it took so long! I had to download a python environment file as I didn't have one (I thought I did), it generated no output so that's good, do I need to do anything else now?

**Comment by hicupalot** [comment]
> > 
> 
> Thanks for the help and sorry it took so long! I had to download a python environment file as I didn't have one (I thought I did), it generated no output so that's good, do I need to do anything else now?

Wait I'll commit the auto-generated file

**Comment by hicupalot** [comment]
> Don't worry :) Go into the `resources` directory and use Python to run `generate_resources.py`. In your terminal:
> 
> ```
> $ python generate_resources.py
> # or on windows with the py wrapper command
> > py generate_resources.py
> ```
> 
> The script has no output if it runs correctly, just updates `src/autogenerated/ResourcesAutogen.cpp`,`.hpp` and `resources/resources_autogen.qrc`.
> 
> PS: on some Linux distributions you might need to try `python3` instead of `python`, the Windows `py` wrapper should just work, I've never used it.

I've committed the resource files now! Thanks again for all your help 😄

**Comment by hicupalot** [comment]
All checks have passed! Thank you for all your help on it once again

**Review by Mm2PL — APPROVED** [review]

**Pull request merged**
