### PR TITLE
Updated minimum required Qt versions

### PR DESCRIPTION
**Pull request by zneix**
Pull request checklist:

- [x] `CHANGELOG.md` was updated, if applicable

# Description

- Updated minimum required and latest Qt versions
- Added Qt version check to chatterino.pro

As discused on Chatterino Discord, we now have methods in our code such as [QOalette#placeholderText](https://doc.qt.io/qt-5/qpalette.html#placeholderText) in https://github.com/Chatterino/chatterino2/blob/master/src/widgets/splits/Split.cpp#L321-L322 which were introduced in Qt 5.12.0, updated documentation to reflect those changes.

### CODE REVIEW

**Comment by zneix** [comment]
Darn, I didn't notice #2208 before opening this PR.

**Comment by swills** [comment]
Duplicates #2210 but maybe this one is better

**Comment by swills** [comment]
Yeah, I like this one better, closing #2208

**Review by pajlada — APPROVED** [review]
:+1: Looks good to me!

**Pull request merged**
