### PR TITLE
Fix Ctrl+Backspace bug after Select All in chat search popup

### LINKED ISSUE #4461: Ctrl+Backspace not working properly in "Search in chat's history" after Select All
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

Instead of delete, it removes Select All highlight and move the text cursor indicator all the way back to the left.

Reproduction steps:

- Open a random chat
- Press Ctrl+F to search for history
- Type in random words `asd`
- Press Ctrl+A or Double Click input box to Select All then Ctrl+Backspace

It works normally:

- in chat.
- Select All then Backspace without Ctrl
- Ctrl+Backspace without Select All

### Screenshots

https://user-images.githubusercontent.com/75530836/226168196-4e4b4f9f-ceb3-4194-b8f9-b6b0dafbf26f.mp4

### OS and Chatterino Version

Chatterino 2.4.2 (commit c8204ef7) built with Qt 5.15.2, Windows SDK, MSVC 193431942, Crashpad Running on Windows 10 Version 2009, kernel: 10.0.19045

### PR DESCRIPTION
**Pull request by vchuynh**
# Description

fixes #4461

PR fixes Ctrl+Backspace not working properly in chat search popup
* Adds event filter to SearchPopup class.  Filters for Ctrl+Backspace and clears text if entire text is selected.

### CODE REVIEW

**Comment by pajlada** [comment]
Do you see anything potentially bad with this change @Mm2PL? I don't think we do hotkeys on inputs other than the split input one so this should be alright

**Review by Mm2PL — APPROVED** [review]
LGTM

**Review by Felanbird — COMMENTED** [review]
works on 🅱️ indows

**Review by Felanbird — APPROVED** [review]

**Comment by Mm2PL** [comment]
@vchuynh,
Thank you! As a first-time contributor, you can now add yourself to the contributors list that's shown inside the About page in Chatterino.

If you want this, you can open a new PR where you modify the `resources/contributors.txt` file and add yourself to the list. Make sure to read the comments at the top for instructions.

Please create new branches (from our `master`) for new PRs. My suggestion would be discarding all commits from your `master` and replacing it with upstream:
```console
$ git remote add upstream https://github.com/Chatterino/chatterino2
$ git fetch --all
$ git checkout master
$ git reset --hard upstream/master
```

For new PRs, I just use:
```console
$ # assuming origin is your remote name (which by default it is)
$ git checkout -b <new-branch-name>
$ # ... do the changes ...
$ git push origin <new-branch-name>
$ # ... do more changes ...
$ git push
```

**Pull request merged**
