### PR TITLE
Larger user card drag area

### LINKED ISSUE #2170: User card issue
User cards only dragging on certain areas.

1) Open someones user card
2) Try to drag the user card anywhere but outside the red box i show in the screenshot

https://i.imgur.com/ZcVQapX.jpeg

Chatterino Nightly 2.2.3-beta (commit 0eed45ae6, )

Windows 10

I'm not sure if this is how its supposed to be or if its a bug.

### PR DESCRIPTION
**Pull request by goldbattle**
Pull request checklist:

- [x] `CHANGELOG.md` was updated, if applicable

# Description

Currently the user profile card has a very small drag area towards the top (I am on windows 10). I also see HasanAbi struggle with this on stream when trying to drag the user card. This adds a mouse callback which allows for dragging if a user clicks anyplace in the window. There is also a small deadzone to prevent from people dragging the window when they really just wanted to click on something.

Before:

https://user-images.githubusercontent.com/2222562/149598133-7200b085-81f6-43a0-9590-04ed06ac55ef.mp4

After:

https://user-images.githubusercontent.com/2222562/149598175-366ab3c7-a016-41ee-9129-729beb8e19a4.mp4

[Felanbird]: Fixes #2170 (tested with 150% resolution as well just to be sure)

### CODE REVIEW

**Review by Felanbird — APPROVED** [review]
Needs a changelog but otherwise the functionality works as intended 👍 
image

**Comment by pajlada** [comment]
:nerd_face: Does not work as expected on Linux using i3.
Calling `move` from within `mouseMoveEvent` will cause another `mouseMoveEvent` to occur, creating a potential infinite recursion.
Windows might be better at handling it, deduplicating the move events or something.


<details>
  <summary>My patch for a decent Linux+i3 experience looks like this</summary>

```patch
diff --git a/lib/qtkeychain b/lib/qtkeychain
--- a/lib/qtkeychain
+++ b/lib/qtkeychain
@@ -1 +1 @@
-Subproject commit de954627363b0b4bff9a2616f1a409b7e14d5df9
+Subproject commit de954627363b0b4bff9a2616f1a409b7e14d5df9-dirty
diff --git a/src/widgets/dialogs/UserInfoPopup.cpp b/src/widgets/dialogs/UserInfoPopup.cpp
index bab6c307..3dd85cd1 100644
--- a/src/widgets/dialogs/UserInfoPopup.cpp
+++ b/src/widgets/dialogs/UserInfoPopup.cpp
@@ -32,6 +32,8 @@
 #include <QNetworkAccessManager>
 #include <QNetworkReply>
 
+#include <chrono>
+
 const QString TEXT_VIEWS("Views: %1");
 const QString TEXT_FOLLOWERS("Followers: %1");
 const QString TEXT_CREATED("Created: %1");
@@ -133,10 +135,10 @@ UserInfoPopup::UserInfoPopup(bool closeAutomatically, QWidget *parent)
                                     : userInfoPopupFlags,
                  parent)
     , hack_(new bool)
+    , dragTimer_(this)
 {
     this->setWindowTitle("Usercard");
     this->setStayInScreenRect(true);
-    this->setMouseTracking(true);
 
     if (closeAutomatically)
         this->setActionOnFocusLoss(BaseWindow::Delete);
@@ -429,6 +431,21 @@ UserInfoPopup::UserInfoPopup(bool closeAutomatically, QWidget *parent)
 
     this->installEvents();
     this->setSizePolicy(QSizePolicy::Ignored, QSizePolicy::Policy::Ignored);
+
+    this->dragTimer_.callOnTimeout(
+        [this, hack = std::weak_ptr<bool>(this->hack_)] {
+            if (!hack.lock())
+            {
+                // Ensure this timer is never called after the object has been destroyed
+                return;
+            }
+            if (!this->isMoving_)
+            {
+                return;
+            }
+
+            this->move(this->requestedDragPos_);
+        });
 }
 
 void UserInfoPopup::themeChangedEvent()
@@ -458,15 +475,16 @@ void UserInfoPopup::mousePressEvent(QMouseEvent *event)
 {
     if (event->button() == Qt::MouseButton::LeftButton)
     {
-        this->isDragging_ = true;
+        this->dragTimer_.start(std::chrono::milliseconds(17));
         this->startPosDrag_ = event->pos();
+        this->movingRelativePos = event->localPos();
     }
 }
 
 void UserInfoPopup::mouseReleaseEvent(QMouseEvent *event)
 {
-    this->isDragging_ = false;
     this->isMoving_ = false;
+    this->dragTimer_.stop();
 }
 
 void UserInfoPopup::mouseMoveEvent(QMouseEvent *event)
@@ -477,7 +495,8 @@ void UserInfoPopup::mouseMoveEvent(QMouseEvent *event)
     auto movePos = event->pos() - this->startPosDrag_;
     if (this->isMoving_ || movePos.manhattanLength() > 10.0)
     {
-        move(window()->pos() + movePos);
+        this->requestedDragPos_ =
+            (event->screenPos() - this->movingRelativePos).toPoint();
         this->isMoving_ = true;
     }
 }
diff --git a/src/widgets/dialogs/UserInfoPopup.hpp b/src/widgets/dialogs/UserInfoPopup.hpp
index 0d7874af..34e2cff1 100644
--- a/src/widgets/dialogs/UserInfoPopup.hpp
+++ b/src/widgets/dialogs/UserInfoPopup.hpp
@@ -44,10 +44,18 @@ private:
     QString avatarUrl_;
     ChannelPtr channel_;
 
-    bool isDragging_ = false;
+    // isMoving_ is set to true if the user is holding the left mouse button down and has moved the mouse a small amount away from the original click point (startPosDrag_)
     bool isMoving_ = false;
+    // startPosDrag_ is the coordinates where the user originally pressed the mouse button down to start dragging
     QPoint startPosDrag_;
 
+    // requestDragPos_ is the final screen coordinates where the widget should be moved to.
+    // Takes the relative position of where the user originally clicked the widget into account
+    QPoint requestedDragPos_;
+
+    // dragTimer_ is called ~60 times per second once the user has initiated dragging
+    QTimer dragTimer_;
+
     pajlada::Signals::NoArgSignal userStateChanged_;
 
     std::unique_ptr<pajlada::Signals::ScopedConnection> refreshConnection_;
```
</details>

Please try this patch out on Windows to make sure it works as expected, then I'll re-review it

**Comment by goldbattle** [comment]
Patch worked well on windows, I think the logic is good too.

**Comment by Felanbird** [comment]
As noted this patch seems perfectly fine on Windows.

Here's my changelog variation I forgot to suggest 🤷 
`- Bugfix: Fixed being unable to drag the user card window from certain spots. (#3508)`

**Review by pajlada — APPROVED** [review]
Confirmed that this change works as expected on macOS both with the "automatically close popup when it loses focus" enabled and disabled

**Pull request merged**
