### PR TITLE
Bump macOS minimum version to 10.14

### PR DESCRIPTION
**Pull request by fanway**
Pull request checklist:

- [x] `CHANGELOG.md` was updated, if applicable

# Description

Right now minimum macOS version is 10.13. For example some external libraries (boost, openssl) have brew formulas only for 10.14 (Mojave). 
Also it would introduce full C++17 (currently used) support for apple clang, which will be useful for example in https://github.com/Chatterino/chatterino2/pull/2368#pullrequestreview-573454781
Maybe it should be bumped to only 10.14 for more compatibility, let me know if you think so.

### CODE REVIEW

**Comment by zneix** [comment]
I know it's not specified yet, but maybe you should also include this information regarding minimum mac version in `BUILDING_ON_MAC.md` document.

**Comment by pajlada** [comment]
I think 10.14 makes more sense in that case - staying in line with whatever brew decides to do seems like a good choice

**Comment by fanway** [comment]
@pajlada ye, i agree, 10.14 seems more reasonable, do you think it worth to add information about minimum version to `BUILDING_ON_MAC.md` as @zneix mentioned?

**Comment by pajlada** [comment]
> @pajlada ye, i agree, 10.14 seems more reasonable, do you think it worth to add information about minimum version to `BUILDING_ON_MAC.md` as @zneix mentioned?

yeah I think so - I took the freedom of just adding that note to `BUILDING_ON_MAC.md` and pushing it to your branch

**Pull request merged**
