### PR TITLE
Show all global FFZ badges of a user

### PR DESCRIPTION
**Pull request by Jaxkey**
Pull request checklist:

- [X] `CHANGELOG.md` was updated, if applicable

# Description

In Chatterino, a maximum of one global FFZ badge appears at a time.

Moobot has both the `Bot` & `FFZ Supporter` global FFZ Badges.

In Chatterino, the `Bot` badge is missing and only one FFZ badge appears.

Changed `badgeMap` to store a vector of ID's in its second position for each FFZ badge a user has (previously only stored a single ID).
Changed `appendFfzBadges()` to loop through each FFZ badge a user has.

Updated version:

### To Reproduce

Have a user with multiple global FFZ badges send a chat message

### CODE REVIEW

**Comment by Felanbird** [comment]
I'm not sure if this is the correct approach, the FFZ Bot badges we load in Chatterino are a relic of the past and purely appear because they are in the same API as supporter badges. 
I'm wondering how this will effect any future implementation of #2241.

**Comment by Infinitay** [comment]
Jumping on to mention IIRC one service _combines_ a bot badge with a mod badge if that user is defined as a bot of a channel. Not sure if it's specific to BTTV or FFZ who combines them.

**Comment by pajlada** [comment]
This doesn't really conflict with the transition to v2 since I don't think anyone is working on that right now, so I'm happy to merge this feature in. Will push a little commit cleaning up the code at the same time as I solve the merge conflict, then let @Jaxkey  get the last review in

**Review by pajlada — APPROVED** [review]
Works as expected :+1: 
Happy to merge upon your approval of my changes @Jaxkey 

image

**Comment by Jaxkey** [comment]
Looks good @pajlada. Merge it 👍

**Pull request merged**
