### PR TITLE
Strip leading @ and trailing , from /user and /usercard commands

### PR DESCRIPTION
**Pull request by sando**
Pull request checklist:

- [x] `CHANGELOG.md` was updated, if applicable

# Description

Strip the leading `@` from the username when using the `/user` and `/usercard` commands. Fixes a minor annoyance when these commands are used along with the *Only search for username autocompletion with an @* option.

### CODE REVIEW

**Comment by apa420** [comment]
wouldn't it just be better to take the @ as input in the /user and /usercard commands instead of stripping the @?

**Comment by sando** [comment]
> wouldn't it just be better to take the @ as input in the /user and /usercard commands instead of stripping the @?

Not sure if I understand what you mean here - keeping the @ opens invalid links in user/usercard.

Admittedly I didn't think about when mentioning users with a comma is enabled, but the option doesn't appear to affect it in this case, e.g. typing `/user username` then tab doesn't append with a comma anyway

**Comment by apa420** [comment]
I was thinking maybe handling it in the /user or /usercard command, but it's really up to preference I guess.

**Comment by ALazyMeme** [comment]
What about the following `,`? Should that be added in the same pr?

**Comment by Felanbird** [comment]
> What about the following `,`? Should that be added in the same pr?

The `,` no longer follows when the tab completion isn't in the first position thanks to the changes implemented in #3060.

**Review by Felanbird — APPROVED** [review]
Functionality works as intended. 👍

Before this PR:
image

Now:
image
urls work too but extra screenshots

**Comment by Felanbird** [comment]
I did notice one thing specific to `/user`, this doesn't fix `/user @username @channel` I'm not sure if anybody actually ever uses it like this? but it might be nice to fix while we are at it.

**Comment by sando** [comment]
I personally don't use it that way, but it's a good idea

**Review by Felanbird — APPROVED** [review]

**Review by apa420 — APPROVED** [review]
Ignore my previous comments, I didn't read the code and the description confused me. I thought you had stripped the @ while typing the message. For some reason I thought this has to do with autocomplete since you were writing about @'ing people.

LGTM!

**Review by Mm2PL — APPROVED** [review]
Lgtm

**Review by pajlada — APPROVED** [review]

**Comment by sando** [comment]
LGTM 👍

**Comment by brian6932** [comment]
Can we do this with /streamlink as well?

**Pull request merged**
