### PR TITLE
Fix split focusing being broken in certain circumstances when the "Show input when it's empty" setting was disabled

### LINKED ISSUE #2714: Chat split not regaining focus after closing search window using ESC
**Describe the bug**
This bug only occurs when the option "Show input when it's empty" is disabled in settings.

When opening the search window using STRG+F and closing it again using ESC, chatterino doesn't give focus back to the split being searched. Since regaining focus does work when theres something entered in the chat field, this is probably due to it trying to focus the text field, which is at that time still hidden

**To reproduce**
1. Disable "Show input when it's empty"
2. Open the search window while not having anything entered in the input field
3. Close the search window using ESC
4. The currently active split does not regain focus

**Chatterino version**
Chatterino 2.3.0 (commit 9c41adca2)

**Operating system**
macOS Big Sur 11.0.1 (20B50)

### LINKED ISSUE #2844: Some keybindings stop working after refocusing chatterino's window
**Describe your issue**
While the option "Show input when it's empty" is turned OFF in the settings, a few of the keybinds ("F5" to reload emotes, for example) stop working after unfocusing chatterino's window and refocusing.

Steps to reproduce:
- Go to Settings --> General --> Chat and uncheck  "Show input when it's empty"
- Focus on a different window, then regain focus on chatterino's window.
- Try using a keybind like "F5"

The problem can be fixed temporarily by switching to a different tab as shown in the second screencast.

**Screenshots**

Behaviour while setting is turned on: (expected behaviour)

https://user-images.githubusercontent.com/16579297/120122374-b2997500-c1a8-11eb-9efb-90f72e0aef5e.mp4

Behaviour while setting is turned off: 

https://user-images.githubusercontent.com/16579297/120122414-d8267e80-c1a8-11eb-880f-952403814a37.mp4

**OS and Chatterino Version**
Arch Linux, Chatterino Nightly 2.3.2 (commit 57354283)
Dwm 6.2 as the window manager

**Additional information**

List of hotkeys affected by this issue (from the list in Settings --> Keybinds):
- Ctrl+W
- Ctrl+G
- Ctrl+R
- Ctrl+F
- Ctrl+F5
- Alt+X
The ones not mentioned do seem to work

### PR DESCRIPTION
**Pull request by pajlada**
Pull request checklist:

- [x] `CHANGELOG.md` was updated, if applicable

# Description

- Make IndirectChannel::get const
- Fix split focusing being broken in certain circumstances when the "Show input when it's empty" setting was disabled.

Fixes #2844 
Fixes #2714

### CODE REVIEW

**Comment by pajlada** [comment]
Relevant testers: @cWve @gempir @brian6932

**Review by zneix — APPROVED** [review]
Couldn't spot any quirks in the code itself and it works as intended :+1:

**Comment by gempir** [comment]
Works exactly as I would expect it to work! Thank you, this thing was really bothering me.

**Review by LosFarmosCTL — APPROVED** [review]
I can finally enable that setting again, very nice fix.

**Comment by brian6932** [comment]
Works for me 👍

**Comment by cWve** [comment]
Thank you pajlada, I can confirm it now works on Linux using sway :+1:

**Review by Felanbird — APPROVED** [review]
Issue seems to be resolved, can no longer replicate Chatterino not properly refocusing.

**Pull request merged**
