### PR TITLE
gentoo linux install instructions

### PR DESCRIPTION
**Pull request by absurdsec**
Pull request checklist:

- [ ] `CHANGELOG.md` was updated, if applicable

# Description

added gentoo linux install instructions in BUILDING_ON_LINUX.md

### CODE REVIEW

**Comment by leon-richardt** [comment]
I would prefer if this were hosted on a Chatterino-owned repo

**Comment by absurdsec** [comment]
sure whatever you think is better

**Comment by alazymeme** [comment]
Have we progressed any further with moving the files to the pr so it is hosted on a Chatterino-owned repo?

**Comment by ALazyMeme** [comment]
Gentoo has some official options: https://gitweb.gentoo.org/repo/gentoo.git & https://github.com/gentoo/gentoo & https://packages.gentoo.org/

**Comment by ALazyMeme** [comment]
image

**Pull request closed without merging**
