### PR TITLE
fix: update color of usernames & boldness of usernames on the fly

### LINKED ISSUE #2637: Disabling Color @username does not disable already colored usernames, unlike Bold @username
**Describe the bug**
Disabling Color @username does not disable already colored usernames, unlike Bold @username

**To reproduce**
1. @ yourself
2. turn off the "Color @username" in the settings.
3. color of previous @ usernames does not change.

**Chatterino version**
Chatterino 2.3.0 (commit 58017a754)

**Operating system**
Windows 10 64-Bit

### PR DESCRIPTION
**Pull request by pajlada**
Boldness was already covered before

Fixes #2637

### CODE REVIEW

**Comment by pajlada** [comment]
This should be ready for a review now @Mm2PL if you want to take a peek

To test, mention a user in a normal & a `/me` message, then flick the `Bold @usernames` and `Color @usernames` settings on and off

**Review by Mm2PL — APPROVED** [review]
Works as expected on Twitch and IRC

**Review by Mm2PL — COMMENTED** [review]
A mistake was made: I can't copy username text

**Review by Mm2PL — CHANGES_REQUESTED** [review]
(misclick)

**Review by Mm2PL — APPROVED** [review]
Everything including copying messages works now. LGTM

**Pull request merged**
